/* eslint-disable @typescript-eslint/no-explicit-any */
import type { InfoEntry } from "@/lib/types";
import { INFO_DB_EN } from "@/lib/info-db-en";

export type Lang = "ko" | "en";

const INFO_DB_KO: Record<string, InfoEntry> = {
  web_api: {
    title:"웹/API 서비스",
    summary:"가장 일반적인 형태. 사용자 요청 → 서버 처리 → 응답 패턴입니다.",
    services:[
      { name:"ALB", role:"트래픽을 여러 서버에 분산", connects:"→ ECS/EC2 연결" },
      { name:"ECS Fargate / Lambda", role:"실제 코드 실행", connects:"→ DB, S3에 데이터 저장" },
      { name:"RDS / Aurora", role:"회원, 게시글 등 구조화된 데이터 저장", connects:"→ 앱 서버에서 쿼리" },
      { name:"CloudFront", role:"정적 파일(이미지, JS) 전 세계 빠르게 전달", connects:"→ ALB 또는 S3 오리진" },
    ],
    flow:"사용자 → CloudFront → ALB → ECS(앱) → RDS(DB)",
    tip:"규모가 커지면 ALB 뒤에 서비스를 여러 개(인증, 상품, 주문)로 분리합니다.",
  },
  ecommerce: {
    title:"이커머스 / 결제",
    summary:"돈이 오가는 서비스. 데이터 정합성과 결제 안전이 최우선입니다.",
    services:[
      { name:"ALB + WAF", role:"외부 트래픽 수신 및 공격 차단", connects:"→ 서비스별 라우팅" },
      { name:"ECS Fargate", role:"상품·주문·결제 서비스 각각 독립 실행", connects:"→ Aurora, SQS 연결" },
      { name:"Aurora PostgreSQL", role:"주문/결제 데이터 SoT (단 하나의 진실)", connects:"→ Multi-AZ로 장애 자동 복구" },
      { name:"ElastiCache Redis", role:"장바구니, 세션 저장, 재고 임시 잠금", connects:"→ 앱 서버에서 원자적 조작" },
      { name:"SQS + Lambda", role:"결제 완료 후 이메일·배송 알림 비동기 처리", connects:"→ SNS 팬아웃으로 여러 큐에 전달" },
    ],
    flow:"사용자 → CloudFront+WAF → ALB → 결제서비스 → Aurora (SoT) → SQS → Lambda(알림)",
    tip:"결제 서비스는 절대 Spot 인스턴스를 쓰면 안 됩니다. 처리 중 종료되면 데이터 불일치가 생깁니다.",
  },
  ticketing: {
    title:"티켓팅 / 예약",
    summary:"수만 명이 동시에 같은 좌석을 차지하려는 서비스. 동시성 제어가 핵심입니다.",
    services:[
      { name:"WAF + Bot Control", role:"매크로·자동화 봇 차단", connects:"→ CloudFront 앞단에 위치" },
      { name:"ElastiCache Redis", role:"좌석 임시 잠금 (SET NX: 이미 잡히면 실패)", connects:"→ SET NX 원자적 연산으로 중복 방지" },
      { name:"SQS (대기열)", role:"동시 요청을 줄 세워 순서대로 처리", connects:"→ Worker가 SQS에서 꺼내 처리" },
      { name:"Aurora PostgreSQL", role:"최종 예매 확정 데이터 저장", connects:"→ 트랜잭션으로 좌석 최종 확정" },
      { name:"Lambda", role:"QR코드 생성, 이메일 발송 등 후처리", connects:"→ SNS 이벤트 수신 후 실행" },
    ],
    flow:"사용자 → WAF(봇차단) → 대기열 서버 → Redis(좌석잠금) → Aurora(확정) → Lambda(QR발송)",
    tip:"대기열 서버는 Fargate Spot 사용 가능(Stateless). 결제·확정 서버는 절대 금지.",
  },
  realtime: {
    title:"실시간 서비스",
    summary:"채팅, 게임, 라이브처럼 지연이 0에 가까워야 하는 서비스. 연결 유지가 핵심입니다.",
    services:[
      { name:"NLB", role:"TCP/WebSocket 연결 유지 (ALB보다 빠름)", connects:"→ 게임·채팅 서버 연결" },
      { name:"API Gateway WebSocket", role:"서버리스 WebSocket 연결 관리", connects:"→ Lambda로 메시지 처리" },
      { name:"ElastiCache Redis Pub/Sub", role:"서버 간 메시지 브로드캐스트", connects:"→ 채팅방 메시지를 모든 서버에 전달" },
      { name:"Kinesis Data Streams", role:"실시간 이벤트 스트림 처리", connects:"→ 게임 이벤트, 클릭 로그 실시간 분석" },
      { name:"DynamoDB", role:"접속 상태, 채팅 기록 저장 (낮은 레이턴시)", connects:"→ DAX 캐시와 함께 마이크로초 응답" },
    ],
    flow:"사용자 ← WebSocket → NLB → 게임서버 ← Redis Pub/Sub → 다른 서버",
    tip:"HTTP가 아닌 WebSocket이나 TCP를 써야 하면 ALB 대신 NLB를 검토하세요.",
  },
  data: {
    title:"데이터 파이프라인",
    summary:"데이터를 모으고, 가공하고, 저장하는 백엔드 중심 서비스. 사용자 대면 UI가 없는 경우가 많습니다.",
    services:[
      { name:"Kinesis Data Streams / MSK", role:"데이터 실시간 수집·스트리밍", connects:"→ Kinesis Firehose로 S3에 저장" },
      { name:"Lambda / AWS Glue", role:"데이터 변환·정제(ETL)", connects:"→ S3 데이터를 읽어 변환 후 저장" },
      { name:"S3 (Data Lake)", role:"원본·가공 데이터 저장", connects:"→ Athena, Redshift로 분석" },
      { name:"Amazon Redshift", role:"대규모 데이터 분석 웨어하우스", connects:"→ QuickSight로 시각화" },
      { name:"AWS Batch / ECS", role:"대용량 배치 처리 (ML 학습 등)", connects:"→ S3에서 읽고 결과를 S3에 저장" },
    ],
    flow:"데이터소스 → Kinesis → Lambda(변환) → S3(저장) → Athena/Redshift(분석)",
    tip:"저장 비용이 크므로 S3 Intelligent-Tiering과 Lifecycle 정책으로 오래된 데이터를 Glacier로 이동하세요.",
  },
  saas: {
    title:"SaaS / 멀티 테넌트 플랫폼",
    summary:"여러 회사(테넌트)가 각자의 데이터를 사용하는 서비스. 테넌트 간 데이터 격리가 핵심입니다.",
    services:[
      { name:"Cognito", role:"테넌트별 회원가입·로그인 관리", connects:"→ JWT 토큰에 테넌트 ID 포함" },
      { name:"API Gateway", role:"테넌트별 Rate Limit 적용", connects:"→ Lambda로 요청 전달" },
      { name:"Aurora (Row-Level Security)", role:"DB 한 개에 모든 테넌트 데이터 저장, 격리", connects:"→ 테넌트 ID로 행 수준 접근 제어" },
      { name:"S3 (테넌트별 접두사)", role:"파일 격리 저장", connects:"→ 테넌트ID/파일명 구조로 분리" },
      { name:"CloudWatch (테넌트별 메트릭)", role:"테넌트별 사용량 모니터링", connects:"→ 과금 계산에 활용" },
    ],
    flow:"테넌트A 사용자 → Cognito(인증) → API Gateway(Rate Limit) → Lambda → Aurora(RLS로 격리)",
    tip:"대형 테넌트는 별도 DB 인스턴스를 주는 '테넌트별 DB' 전략도 고려하세요.",
  },
  iot: {
    title:"IoT / 디바이스 연동",
    summary:"수천~수만 대의 장치에서 데이터가 계속 올라오는 서비스. 대용량 수집과 낮은 지연이 중요합니다.",
    services:[
      { name:"AWS IoT Core", role:"디바이스 연결 관리 (MQTT 프로토콜)", connects:"→ Kinesis, Lambda, S3로 라우팅" },
      { name:"Kinesis Data Streams", role:"초당 수만 건 센서 데이터 스트리밍", connects:"→ Lambda로 실시간 처리" },
      { name:"DynamoDB", role:"디바이스 최신 상태 저장 (빠른 조회)", connects:"→ TTL로 오래된 상태 자동 삭제" },
      { name:"Timestream", role:"시계열 센서 데이터 장기 보관·분석", connects:"→ Grafana로 시각화" },
      { name:"Lambda", role:"이상 감지, 알림 발송, 자동 제어", connects:"→ SNS로 알림 전달" },
    ],
    flow:"디바이스 → IoT Core(MQTT) → Kinesis → Lambda(처리) → DynamoDB(상태) + Timestream(이력)",
    tip:"MQTT는 배터리 절약에 최적화된 경량 프로토콜입니다. REST보다 데이터 전송량이 훨씬 적습니다.",
  },
  internal: {
    title:"사내 도구 / 어드민",
    summary:"직원만 쓰는 서비스. 높은 가용성보다 빠른 개발과 낮은 비용이 우선입니다.",
    services:[
      { name:"SSO (IAM Identity Center)", role:"사내 계정으로 로그인 (AD/Google 연동)", connects:"→ AWS 콘솔 및 내부 앱 접근 통합" },
      { name:"VPN / Direct Connect", role:"사내망에서만 접근 가능하게 격리", connects:"→ 외부 인터넷 차단" },
      { name:"App Runner / ECS (소규모)", role:"단순 웹 앱 실행", connects:"→ RDS에 데이터 저장" },
      { name:"RDS (Single-AZ)", role:"비용 절감형 DB", connects:"→ 다운타임 허용 범위 내에서 운용" },
    ],
    flow:"직원 VPN → ALB(내부) → 앱 서버 → RDS",
    tip:"외부 공개가 필요 없으니 NAT Gateway나 CloudFront 같은 비용 항목을 최소화할 수 있습니다.",
  },

  /* ── 데이터 민감도 ────────────────────────────── */
  public: {
    title:"공개 데이터",
    summary:"누구나 봐도 되는 데이터. 보안 설계가 단순해집니다.",
    services:[
      { name:"S3 퍼블릭 버킷", role:"콘텐츠 공개 제공", connects:"→ CloudFront로 전달" },
      { name:"CloudFront", role:"전 세계 빠른 배포", connects:"→ S3 또는 ALB 오리진" },
    ],
    flow:"사용자 → CloudFront → S3(공개)",
    tip:"공개 데이터라도 API 키나 설정 파일은 절대 함께 저장하지 마세요.",
  },
  sensitive: {
    title:"개인정보 (PII)",
    summary:"이름·연락처·주소 등 법적 보호 대상 데이터. 개인정보보호법 적용.",
    services:[
      { name:"KMS", role:"DB·S3 저장 데이터 암호화", connects:"→ Aurora, S3에 암호화 적용" },
      { name:"VPC + 격리 서브넷", role:"DB를 인터넷에서 완전 차단", connects:"→ 앱 서버에서만 접근 가능" },
      { name:"IAM + Secrets Manager", role:"DB 접속 비밀번호 안전 관리", connects:"→ 앱이 런타임에 비밀번호 조회" },
      { name:"CloudTrail", role:"누가 언제 어떤 데이터 접근했는지 기록", connects:"→ S3에 감사 로그 보관" },
    ],
    flow:"앱 → Secrets Manager(비밀번호 조회) → KMS(복호화 키) → Aurora(암호화 DB)",
    tip:"국내 서비스라면 개인정보보호법에 따라 개인정보 처리방침 고지 및 동의 수집이 필요합니다.",
  },
  critical: {
    title:"결제 / 금융 / 의료 데이터",
    summary:"유출 시 법적 제재와 막대한 피해가 발생. 가장 강력한 보호 필요.",
    services:[
      { name:"KMS (Customer Managed Key)", role:"고객이 직접 암호화 키 관리", connects:"→ 키 접근 권한을 특정 역할에만 부여" },
      { name:"CloudTrail + AWS Config", role:"모든 API 호출·설정 변경 감사 기록", connects:"→ S3 장기 보관, 변조 방지" },
      { name:"Security Hub + GuardDuty", role:"보안 이상 자동 탐지", connects:"→ EventBridge로 즉시 알림" },
      { name:"VPC + 완전 격리 서브넷", role:"DB·결제 시스템 완전 격리", connects:"→ 인터넷 경로 없음, VPC Endpoint만 허용" },
      { name:"WAF + Shield Advanced", role:"DDoS·해킹 시도 방어", connects:"→ CloudFront·ALB 앞단" },
    ],
    flow:"결제 앱 → KMS(암호화) → Aurora(격리 서브넷) + CloudTrail(모든 접근 로깅)",
    tip:"PCI-DSS 인증이 필요하면 카드 데이터를 직접 처리하지 않고 PG사(토스페이먼츠 등)에 위임하는 것이 훨씬 쉽습니다.",
  },

  /* ── 가용성 ──────────────────────────────────── */
  serverless: {
    title:"서버리스 아키텍처",
    summary:"서버를 직접 관리하지 않고 코드만 업로드. AWS가 실행·확장·복구를 담당.",
    services:[
      { name:"Lambda", role:"함수 단위 코드 실행 (최대 15분)", connects:"→ API Gateway, SQS, SNS, S3 이벤트와 연결" },
      { name:"API Gateway", role:"HTTP 요청을 Lambda로 전달", connects:"→ 인증(Cognito), Rate Limit 내장" },
      { name:"DynamoDB", role:"서버리스에 어울리는 NoSQL DB", connects:"→ Lambda에서 직접 SDK로 접근" },
      { name:"S3", role:"파일 저장 및 정적 웹사이트 호스팅", connects:"→ 파일 업로드 시 Lambda 트리거 가능" },
    ],
    flow:"사용자 → API Gateway → Lambda → DynamoDB/S3",
    tip:"Lambda 콜드스타트(첫 실행 시 약 1초 지연)가 있습니다. 지연에 민감하면 Provisioned Concurrency를 설정하세요.",
  },
  ecs: {
    title:"ECS (Elastic Container Service)",
    summary:"AWS 전용 컨테이너 관리 서비스. Kubernetes보다 단순하고 배우기 쉬움.",
    services:[
      { name:"ECS 클러스터", role:"컨테이너 실행 환경", connects:"→ Fargate 또는 EC2 노드에서 실행" },
      { name:"ECS 서비스", role:"특정 수의 컨테이너 항상 유지", connects:"→ ALB Target Group에 자동 등록/해제" },
      { name:"ECS Task Definition", role:"컨테이너 설정 (이미지, CPU, 메모리, 환경변수)", connects:"→ Secrets Manager에서 비밀번호 가져옴" },
      { name:"ECS Service Discovery", role:"서비스 간 내부 통신 주소 자동 관리", connects:"→ Route 53 프라이빗 호스팅 존 사용" },
    ],
    flow:"Task Definition → ECS Service → Fargate 태스크 → ALB Target Group",
    tip:"ECS는 오케스트레이션 자체는 무료. Fargate 사용 시 실행된 vCPU·메모리 시간만 과금됩니다.",
  },
  eks: {
    title:"EKS (Elastic Kubernetes Service)",
    summary:"업계 표준 Kubernetes를 AWS에서 관리형으로 제공. 강력하지만 복잡.",
    services:[
      { name:"EKS 컨트롤 플레인", role:"클러스터 관리 ($72/월 고정 과금)", connects:"→ 워커 노드(EC2/Fargate) 오케스트레이션" },
      { name:"Karpenter", role:"노드 자동 프로비저닝 (Spot+On-Demand 혼합)", connects:"→ 파드 스케줄링 요청 감지 시 노드 자동 추가" },
      { name:"ALB Ingress Controller", role:"Kubernetes Ingress → AWS ALB 자동 생성", connects:"→ 서비스 배포 시 ALB 규칙 자동 설정" },
      { name:"KEDA", role:"SQS 메시지 수 기반 자동 스케일링", connects:"→ SQS 큐 깊이 → HPA(파드 수) 조정" },
    ],
    flow:"kubectl apply → EKS 컨트롤 플레인 → Karpenter(노드) → 파드 실행 → ALB(트래픽)",
    tip:"EKS는 클러스터 고정 비용($72/월)이 있습니다. 서비스가 10개 미만이면 ECS가 더 경제적입니다.",
  },

  /* ── DB ─────────────────────────────────────── */
  aurora_pg: {
    title:"Aurora PostgreSQL",
    summary:"AWS가 만든 PostgreSQL 호환 고성능 DB. 일반 RDS보다 최대 3배 빠르고 가용성이 높음.",
    services:[
      { name:"Aurora Writer 인스턴스", role:"쓰기(INSERT/UPDATE/DELETE) 처리", connects:"→ 동기식으로 6개 스토리지 노드에 복제" },
      { name:"Aurora Reader 인스턴스", role:"읽기(SELECT) 처리 분산", connects:"→ Writer와 동일한 스토리지를 공유 (지연 < 100ms)" },
      { name:"Aurora Global Database", role:"다른 리전에 1초 미만 지연 복제", connects:"→ 리전 장애 시 수초 내 전환 가능" },
      { name:"Aurora Serverless v2", role:"사용량에 따라 자동 확장/축소", connects:"→ 트래픽 없을 때 최솟값까지 축소 (비용 절감)" },
    ],
    flow:"앱 서버 → Aurora Endpoint(Writer) → 6개 스토리지 노드 복제",
    tip:"Aurora는 스토리지가 10GB 단위로 자동 확장됩니다. 미리 용량을 걱정하지 않아도 됩니다.",
  },
  dynamodb: {
    title:"DynamoDB",
    summary:"AWS의 완전 관리형 NoSQL DB. 무제한 확장, 초고속, 서버리스 친화적.",
    services:[
      { name:"DynamoDB 테이블", role:"기본키(파티션키+정렬키) 기반 데이터 저장", connects:"→ 글로벌 보조 인덱스(GSI)로 다양한 조회 가능" },
      { name:"DynamoDB Streams", role:"데이터 변경 이벤트 실시간 캡처", connects:"→ Lambda 트리거로 변경 시 자동 처리" },
      { name:"DAX (DynamoDB Accelerator)", role:"인메모리 캐시 (마이크로초 응답)", connects:"→ DynamoDB 앞단에 투명하게 캐시" },
      { name:"DynamoDB Global Tables", role:"여러 리전에 동시 복제 (멀티 리전 쓰기)", connects:"→ 가장 가까운 리전에서 읽고 씀" },
    ],
    flow:"앱 → DAX(캐시 확인) → DynamoDB → DynamoDB Streams → Lambda(변경 처리)",
    tip:"DynamoDB는 접근 패턴을 미리 정하고 스키마를 설계해야 합니다. 나중에 접근 패턴을 바꾸기 어렵습니다. 설계 단계에서 신중하게 결정하세요.",
  },
  redis: {
    title:"ElastiCache Redis",
    summary:"인메모리 캐시. DB보다 10~100배 빠른 임시 저장소. 다양한 데이터 구조 지원.",
    services:[
      { name:"Redis 클러스터", role:"데이터를 여러 샤드에 분산 저장", connects:"→ 앱에서 Cluster Mode 엔드포인트로 연결" },
      { name:"Redis Replica", role:"읽기 분산 및 장애 복구", connects:"→ 주 노드 장애 시 레플리카가 승격" },
      { name:"Redis Pub/Sub", role:"서버 간 메시지 브로드캐스트", connects:"→ 채팅, 실시간 알림에 활용" },
    ],
    flow:"앱 → Redis(SET NX 원자적 잠금) → 성공 시 → DB에 확정 저장",
    tip:"Redis는 SoT(진실의 원천)가 아닙니다. Redis가 재시작되면 데이터가 사라질 수 있습니다. 중요한 데이터는 반드시 DB에도 저장하세요.",
  },

  /* ── 메시징 ──────────────────────────────────── */
  sqs: {
    title:"SQS (Simple Queue Service)",
    summary:"처리할 일을 줄 세우는 대기열. 서비스 장애 시에도 메시지가 안전하게 보관됨.",
    services:[
      { name:"SQS Standard 큐", role:"높은 처리량, 최소 1회 전달 (순서 미보장)", connects:"→ 소비자 서비스(Lambda, ECS)가 폴링" },
      { name:"SQS FIFO 큐", role:"순서 보장, 정확히 1회 처리", connects:"→ 결제 등 순서가 중요한 처리에 사용" },
      { name:"DLQ (Dead Letter Queue)", role:"처리 실패한 메시지 별도 보관", connects:"→ CloudWatch 알람으로 DLQ 메시지 수 모니터링" },
    ],
    flow:"생산자(앱) → SQS → 소비자(Lambda/ECS) → 실패 시 → DLQ",
    tip:"DLQ 없는 SQS는 불완전합니다. 처리 실패 메시지가 계속 재시도되다 사라집니다. 반드시 DLQ를 설정하세요.",
  },
  sns: {
    title:"SNS (Simple Notification Service)",
    summary:"하나의 이벤트를 여러 곳에 동시에 전달하는 Pub/Sub 방식.",
    services:[
      { name:"SNS 토픽", role:"이벤트 발행 채널", connects:"→ SQS, Lambda, HTTP, 이메일 등 여러 구독자에게 전달" },
      { name:"SNS 메시지 필터링", role:"구독자별로 필요한 메시지만 수신", connects:"→ 속성(attribute) 기반 필터링" },
    ],
    flow:"결제완료 이벤트 → SNS → 발송큐(SQS) + 적립큐(SQS) + 재고큐(SQS) 동시 전달",
    tip:"SNS 단독으로는 메시지를 저장하지 않습니다. 전달 실패 시 재처리를 원하면 SNS + SQS 조합을 사용하세요.",
  },
  kinesis: {
    title:"Kinesis Data Streams",
    summary:"실시간 대용량 스트리밍. 이미 처리한 데이터도 다시 처리(리플레이) 가능.",
    services:[
      { name:"Kinesis 샤드", role:"스트림 처리 단위 (샤드당 1MB/s 입력)", connects:"→ 샤드 수를 늘려 처리량 확장" },
      { name:"Kinesis Firehose", role:"S3/Redshift로 자동 배달 파이프라인", connects:"→ Kinesis Streams에서 데이터를 받아 저장" },
      { name:"Lambda (소비자)", role:"실시간 데이터 처리·변환", connects:"→ Enhanced Fan-Out으로 여러 Lambda가 동시 소비" },
    ],
    flow:"앱 → Kinesis Streams → Lambda(실시간처리) + Firehose(S3저장)",
    tip:"Kinesis는 기본 24시간, 최대 365일 데이터 보관합니다. 오래된 데이터도 다시 처음부터 처리할 수 있습니다.",
  },
  eventbridge: {
    title:"EventBridge",
    summary:"이벤트를 규칙에 따라 분류·라우팅하는 서비스. 스케줄러 기능도 포함.",
    services:[
      { name:"EventBridge 이벤트 버스", role:"이벤트 수신 및 규칙 기반 라우팅", connects:"→ Lambda, SQS, ECS Task 등으로 전달" },
      { name:"EventBridge Scheduler", role:"cron 스케줄 기반 자동 실행", connects:"→ Lambda, SQS, Step Functions 트리거" },
      { name:"EventBridge Pipes", role:"이벤트 소스와 대상을 파이프로 연결", connects:"→ 필터링·변환·보강 후 대상에 전달" },
    ],
    flow:"AWS 서비스 이벤트 → EventBridge 규칙 → Lambda/SQS/ECS 자동 실행",
    tip:"매일 오전 9시, 매시간 정각 실행 같은 스케줄 작업은 EventBridge Scheduler가 cron보다 훨씬 간편합니다.",
  },

  /* ── 엣지 ─────────────────────────────────────── */
  none_cert: {
    title:"규정 없음",
    summary:"별도 인증이 필요 없는 서비스. 기본 보안 설계로 시작.",
    services:[
      { name:"IAM 최소 권한", role:"각 서비스에 필요한 최소 권한만 부여", connects:"→ 모든 AWS 리소스 접근에 적용" },
      { name:"GuardDuty", role:"비정상 활동 자동 감지", connects:"→ 이상한 API 호출·IP 접근 시 알림" },
      { name:"CloudTrail", role:"모든 API 호출 기록", connects:"→ 보안 사고 발생 시 원인 추적" },
    ],
    flow:"기본 보안 → IAM + SG + CloudTrail + GuardDuty",
    tip:"규정이 없어도 보안 기본기는 지켜야 합니다. 루트 계정 MFA, DB 프라이빗 배치, 비밀번호 환경변수 저장 금지가 3대 기본입니다.",
  },
  pci: {
    title:"PCI-DSS (카드 결제 보안)",
    summary:"신용카드 데이터를 처리하는 경우 필수. 12가지 요구사항을 모두 충족해야 함.",
    services:[
      { name:"카드 데이터 비보유 권장 (PG 위임)", role:"PG사가 카드 정보를 처리하면 PCI 범위가 크게 줄어듦", connects:"→ 토스페이먼츠·KG이니시스 등 PCI 인증 PG사 활용" },
      { name:"네트워크 분할 (CDE 격리)", role:"카드 데이터 환경(CDE)을 별도 서브넷으로 완전 분리", connects:"→ CDE에서 나가는 모든 트래픽 모니터링" },
      { name:"AWS Config + Security Hub", role:"PCI DSS 컴플라이언스 자동 체크", connects:"→ 위반 설정 감지 시 자동 알림·수정" },
    ],
    flow:"카드 정보는 PG사에서 처리 → 토큰만 받아서 Aurora에 저장 → 결제 시 토큰 전달",
    tip:"카드 번호를 직접 받지 않고 PG사 결제창(팝업/리디렉션)을 쓰면 PCI-DSS 적용 범위를 최소화할 수 있습니다.",
  },
  managed: {
    title:"운영 최소화 (AWS 관리형 서비스 위주)",
    summary:"서버 관리보다 서비스 개발에 집중. 가능한 모든 것을 AWS가 관리하게 위임.",
    services:[
      { name:"ECS Fargate", role:"서버 없는 컨테이너 (OS 관리 불필요)", connects:"→ 컨테이너 이미지만 올리면 AWS가 실행" },
      { name:"Aurora Serverless v2", role:"DB 용량 자동 조절 (패치·백업 자동)", connects:"→ 트래픽 없을 때 최솟값으로 자동 축소" },
      { name:"Lambda", role:"서버 없이 코드 실행", connects:"→ API Gateway와 연결해 완전 서버리스 API" },
      { name:"ElastiCache Serverless", role:"캐시 서버 관리 불필요", connects:"→ 용량 걱정 없이 쓴 만큼 과금" },
    ],
    flow:"코드 배포 → AWS가 서버 배정·확장·패치·백업 자동 처리",
    tip:"관리형 서비스는 일반적으로 직접 관리 대비 약간 비쌉니다. 하지만 인력 비용을 고려하면 소규모 팀에서는 훨씬 경제적입니다.",
  },

  /* ── 스토리지 ─────────────────────────────────── */
  s3: {
    title:"Amazon S3",
    summary:"무제한 오브젝트 스토리지. 거의 모든 서비스에서 파일 저장에 사용.",
    services:[
      { name:"S3 버킷", role:"파일 저장 컨테이너", connects:"→ 버킷 정책으로 접근 제어" },
      { name:"S3 Intelligent-Tiering", role:"접근 빈도에 따라 자동으로 저렴한 티어로 이동", connects:"→ 별도 설정 없이 비용 자동 최적화" },
      { name:"S3 Lifecycle", role:"X일 후 Glacier로 이동, Y일 후 삭제", connects:"→ 오래된 로그·백업 자동 정리" },
      { name:"S3 Event Notification", role:"파일 업로드 시 Lambda 자동 실행", connects:"→ 이미지 리사이징, 바이러스 스캔 등" },
    ],
    flow:"앱 → S3 업로드 → S3 이벤트 → Lambda(처리) → 결과를 S3에 저장",
    tip:"S3는 저장 비용보다 API 호출 비용이 더 클 수 있습니다. 작은 파일 수만 개보다 큰 파일 몇 개로 묶는 게 유리합니다.",
  },

  /* ══ 자동 추가 INFO ══ */
  tiny:{title:"소규모 (DAU 1천 미만)",summary:"하루 이용자 1,000명 미만. 스타트업 극초기 또는 사내 도구 수준입니다.",services:[{name:"Lambda / t3.small",role:"소규모에 충분한 저비용 컴퓨팅",connects:"→ 단일 서버로 시작 가능"},{name:"RDS db.t3.micro",role:"소형 DB 인스턴스 월 약 20달러",connects:"→ 단순 조회·저장에 충분"}],flow:"소수 사용자 → ALB → 서버 1대 → DB",tip:"이 규모에선 단순하게 시작하세요. 과도한 인프라는 비용 낭비입니다."},
  small:{title:"소형 서비스 (DAU 1만 미만)",summary:"하루 이용자 1만 명 미만. 대부분 스타트업 초기 단계입니다.",services:[{name:"ECS Fargate 2 Task",role:"서버 관리 없이 컨테이너 운영",connects:"→ 트래픽에 맞게 자동 확장"},{name:"RDS db.t3.medium",role:"충분한 DB 용량",connects:"→ Multi-AZ 고려 시작"}],flow:"사용자 → CloudFront → ALB → ECS(2대) → RDS",tip:"이 단계에서 Multi-AZ DB와 ALB를 미리 구성하면 이후 확장이 훨씬 쉬워집니다."},
  medium:{title:"중형 서비스 (DAU 10만 미만)",summary:"하루 이용자 1~10만 명. 캐시와 오토스케일링이 필요해지는 시점입니다.",services:[{name:"ElastiCache Redis",role:"자주 쓰는 데이터를 빠르게 캐시",connects:"→ DB 부하 70% 절감"},{name:"ECS Auto Scaling",role:"CPU 70% 초과 시 서버 자동 추가",connects:"→ 트래픽 증가 자동 대응"},{name:"Aurora",role:"일반 RDS보다 3배 빠른 고성능 DB",connects:"→ Read Replica로 읽기 분산"}],flow:"사용자 → CDN → ALB → ECS → Redis → Aurora",tip:"이 규모부터 Redis 캐시 도입이 가장 효과적인 성능 개선책입니다."},
  large:{title:"대형 서비스 (DAU 100만 미만)",summary:"하루 이용자 10만~100만 명. 기능별 서비스 분리(MSA)가 필요합니다.",services:[{name:"ECS/EKS 멀티 서비스",role:"주문·결제·인증 서비스 독립 운영",connects:"→ 서비스별 독립 배포·확장"},{name:"Aurora Global",role:"멀티리전 DB 복제",connects:"→ 리전 장애 시 자동 전환"},{name:"CloudFront+WAF",role:"CDN + 공격 차단 필수",connects:"→ 오리진 서버 보호"}],flow:"사용자 → CloudFront+WAF → ALB → MSA → Aurora Multi-AZ",tip:"이 규모에서는 단일 서비스 구조가 병목이 됩니다. 핵심 도메인별 서비스 분리를 시작하세요."},
  xlarge:{title:"초대형 서비스 (DAU 100만+)",summary:"하루 이용자 100만 명 이상. 아키텍처 최적화가 비즈니스 생존과 직결됩니다.",services:[{name:"EKS + Karpenter",role:"수천 개 컨테이너 정밀 관리",connects:"→ 노드 자동 프로비저닝"},{name:"DynamoDB Global Tables",role:"전 세계 무제한 확장 NoSQL",connects:"→ 리전별 자동 복제"},{name:"Shield Advanced",role:"대규모 DDoS 방어",connects:"→ 인프라 보호 SLA"}],flow:"글로벌 사용자 → 지역 엣지 → 서비스 메시 → 분산 DB",tip:"이 규모에서는 아키텍처 결정 하나가 월 수천만 원 차이를 냅니다."},
  low:{title:"낮은 RPS (초당 100 이하)",summary:"1초에 100개 미만의 요청. 내부 도구나 소규모 서비스 수준입니다.",services:[{name:"단일 서버 또는 Lambda",role:"충분한 처리 용량",connects:"→ 오토스케일링 불필요"}],flow:"요청 → 단일 서버 → 응답",tip:"이 수준이면 단일 서버로 충분합니다. 과도한 인프라는 비용 낭비입니다."},
  high:{title:"높은 RPS (초당 1000~10000)",summary:"1초에 1,000~10,000개 요청. 인기 있는 B2C 서비스 수준입니다.",services:[{name:"CloudFront 캐시",role:"정적 요청의 80% 흡수",connects:"→ 오리진 서버 부하 감소"},{name:"ElastiCache Redis",role:"DB 앞단 캐시",connects:"→ DB 직접 쿼리 70% 감소"},{name:"Aurora Read Replica",role:"읽기 전용 DB 복사본",connects:"→ 쓰기·읽기 분리"}],flow:"요청 → CloudFront → ALB → ECS → Redis → Aurora+Replica",tip:"이 RPS에서 캐시 없이 DB만 쓰면 DB가 병목이 됩니다. Redis 도입이 필수입니다."},
  ultra:{title:"초고 RPS (초당 10000+)",summary:"1초에 만 건 이상. 티켓팅·이커머스 피크 또는 대형 플랫폼 수준입니다.",services:[{name:"EKS + Karpenter",role:"수백 개 Pod 수분 내 자동 확장",connects:"→ EC2 노드 즉시 추가"},{name:"DynamoDB",role:"초당 수백만 건 처리 NoSQL",connects:"→ 읽기/쓰기 자동 확장"},{name:"Global Accelerator",role:"전 세계 트래픽 최적 경로",connects:"→ 지연시간 최소화"}],flow:"사용자 → Global Accelerator → 멀티리전 → EKS → DynamoDB",tip:"이 수준 트래픽이 예상된다면 AWS 솔루션 아키텍트에게 사전 검토를 받으세요."},
  steady:{title:"일정한 트래픽",summary:"하루 내내 비슷한 양의 요청. 예측 가능해 인프라 계획이 쉽습니다.",services:[{name:"Reserved Instance",role:"예약 구매로 비용 40% 절감",connects:"→ 안정적 워크로드에 최적"}],flow:"일정한 요청 → 고정 용량 서버 → 응답",tip:"트래픽이 일정하면 Reserved Instance로 비용을 크게 절감할 수 있습니다."},
  spike:{title:"스파이크 트래픽 (예측 가능한 폭증)",summary:"티켓 오픈·특가 행사처럼 특정 시간에 폭발적으로 트래픽이 증가합니다.",services:[{name:"Scheduled Scaling",role:"이벤트 10분 전 서버 미리 늘려놓기",connects:"→ Cold Start 없이 수용"},{name:"WAF Bot Control",role:"이벤트 시 매크로 봇 차단",connects:"→ 정상 사용자만 접근"},{name:"Redis SET NX",role:"동시 선점 방지 원자적 잠금",connects:"→ 이중 판매 방지"}],flow:"이벤트 10분 전 확장 → 폭증 수용 → Redis 잠금 → DB 확정",tip:"스파이크 발생 후 Scale-Out은 이미 늦습니다. 반드시 예약 확장으로 미리 준비하세요."},
  burst:{title:"버스트 트래픽 (예측 불가 폭증)",summary:"언제 폭증할지 모르는 패턴. 바이럴 서비스나 뉴스 언급 시 발생합니다.",services:[{name:"Lambda/Fargate",role:"즉시 확장·트래픽 없으면 0까지 축소",connects:"→ 비용 최소화"},{name:"CloudFront",role:"갑작스런 트래픽을 엣지에서 흡수",connects:"→ 오리진 서버 보호막"},{name:"SQS 버퍼링",role:"폭증 요청을 큐에 담아 순차 처리",connects:"→ DB 과부하 방지"}],flow:"갑작스런 트래픽 → CloudFront → SQS → Lambda(처리) → DB",tip:"예측 불가 버스트에는 Lambda나 Fargate처럼 필요할 때만 실행되는 아키텍처가 최적입니다."},
  business:{title:"업무시간 집중 패턴",summary:"오전 9시~오후 6시에 집중되고 야간·주말은 한산한 패턴. 기업용 서비스에 전형적입니다.",services:[{name:"Scheduled Auto Scaling",role:"야간·주말 서버 자동 축소",connects:"→ 비사용 시간 비용 30~50% 절감"}],flow:"오전 서버 확장 → 업무시간 처리 → 오후 서버 축소",tip:"야간·주말에 서버를 줄이면 월 비용을 30~50% 절감할 수 있습니다."},
  gb:{title:"GB 수준 데이터 (100GB 미만)",summary:"데이터가 100GB 미만인 경우. 일반 RDS나 소형 S3로 충분합니다.",services:[{name:"RDS t3 / S3 Standard",role:"소용량에 적합한 표준 스토리지",connects:"→ 초기 비용 최소화"}],flow:"앱 → RDS(정형) / S3(파일)",tip:"이 용량이면 쿼리 최적화(인덱스 설계)가 성능에 더 큰 영향을 줍니다."},
  tb:{title:"TB 수준 데이터 (100GB~수십TB)",summary:"수십 TB 규모. 비용 최적화와 파티셔닝이 필요합니다.",services:[{name:"S3 Intelligent-Tiering",role:"접근 빈도에 따라 자동으로 저렴한 등급 이동",connects:"→ 별도 설정 없이 비용 절감"},{name:"Aurora Serverless v2",role:"데이터 증가에 맞게 용량 자동 조절",connects:"→ 스토리지 걱정 없이 확장"}],flow:"데이터 → S3(파일) / Aurora(정형) → Glacier(장기 보관)",tip:"오래된 데이터를 S3 Glacier로 이동하면 스토리지 비용을 80%까지 줄일 수 있습니다."},
  solo:{title:"1인 개발자",summary:"혼자 개발하고 운영합니다. 관리 부담 최소화가 최우선입니다.",services:[{name:"Lambda + API Gateway",role:"서버 없이 코드만 올리면 바로 운영",connects:"→ 서버 관리 불필요"},{name:"Aurora Serverless v2",role:"DB 용량·패치 AWS 자동 관리",connects:"→ DB 전문 지식 없어도 운영 가능"}],flow:"코드 작성 → 배포 → AWS가 나머지 처리",tip:"1인 운영에서는 관리형 서비스를 최대한 활용하세요. 서버 관리 시간이 곧 제품 개선 시간입니다."},
  beginner:{title:"AWS 초급",summary:"AWS를 쓴 지 얼마 안 됐거나 기본 기능만 알고 있는 수준입니다.",services:[{name:"ECS Fargate",role:"쿠버네티스 없이 컨테이너 운영",connects:"→ 복잡한 K8s 설정 불필요"},{name:"RDS Managed",role:"DB 패치·백업 AWS 자동 처리",connects:"→ DB 전문 지식 없어도 운영 가능"}],flow:"코드 → ECS 배포 → RDS 연결",tip:"초급 단계에서는 ECS Fargate + Aurora Serverless 조합이 가장 쉽고 안정적입니다."},
  mid:{title:"AWS 중급",summary:"EC2, ECS, RDS 등 주요 서비스를 사용해본 경험이 있습니다.",services:[{name:"ECS + ALB + Auto Scaling",role:"일반적인 웹 서비스 표준 스택",connects:"→ 표준 아키텍처 운영 가능"},{name:"CloudWatch 모니터링",role:"서비스 상태 실시간 알림",connects:"→ 장애 시 빠른 대응"}],flow:"코드 → CI/CD → ECS → RDS + Redis → CloudWatch",tip:"중급 단계에서는 Terraform 또는 CDK로 인프라를 코드로 관리하는 것을 추천합니다."},
  devops:{title:"DevOps 팀 운영",summary:"개발팀이 직접 배포·운영을 담당합니다. CI/CD 자동화와 모니터링이 핵심입니다.",services:[{name:"GitHub Actions / GitLab CI",role:"코드 푸시 → 자동 테스트·배포",connects:"→ 수동 배포 없이 자동화"},{name:"CloudWatch + 알림",role:"장애 즉시 온콜 담당자 알림",connects:"→ SNS → SMS/이메일"}],flow:"개발자 → Git → CI/CD → 자동 배포 → 모니터링",tip:"DevOps 문화의 핵심은 배포를 두려워하지 않는 것입니다. Blue/Green 배포와 빠른 롤백으로 이를 달성하세요."},
  hipaa:{title:"HIPAA (미국 의료정보 보호법)",summary:"미국에서 환자 의료 정보를 다루는 서비스라면 반드시 준수해야 합니다.",services:[{name:"KMS 암호화 필수",role:"환자 데이터 저장·전송 암호화",connects:"→ RDS·S3·EBS 모두 암호화"},{name:"CloudTrail + Config",role:"모든 데이터 접근 감사 로그",connects:"→ 누가 언제 무엇을 접근했는지 기록"},{name:"VPC 완전 격리",role:"의료 데이터 인터넷 차단",connects:"→ VPN 또는 DX만 접근 허용"}],flow:"의료 데이터 → 암호화 저장 → IAM 인증 → CloudTrail 로그",tip:"AWS는 HIPAA BAA를 제공합니다. 시작 전 반드시 서명해야 합니다."},
  gdpr:{title:"GDPR (EU 개인정보 보호 규정)",summary:"EU 거주자의 데이터를 처리하는 서비스라면 국내 기업도 적용됩니다.",services:[{name:"EU 리전 데이터 거주",role:"EU 데이터는 EU 서버에만 저장",connects:"→ 리전 간 데이터 이동 제한"},{name:"S3 Object Lock",role:"데이터 삭제 요청 대응",connects:"→ 사용자 탈퇴 시 30일 내 삭제"}],flow:"EU 사용자 → EU 리전 서버 → 로컬 저장 → 삭제 요청 시 완전 삭제",tip:"GDPR 잊혀질 권리 대응: 사용자 데이터를 별도 PII 저장소에 분리하면 삭제가 쉬워집니다."},
  sox:{title:"SOX (미국 상장사 회계 규정)",summary:"미국 증시 상장 기업이 재무 데이터의 무결성을 보장해야 하는 규정입니다.",services:[{name:"CloudTrail",role:"모든 인프라 변경 감사 로그",connects:"→ 누가 언제 무엇을 변경했는지 기록"},{name:"S3 Object Lock WORM",role:"감사 로그 변조 불가 저장",connects:"→ 5~7년 보존 의무"}],flow:"운영 활동 → CloudTrail 기록 → S3 WORM 저장 → 감사인에게 제출",tip:"CloudTrail은 Organization 레벨에서 켜고, 로그를 별도 감사 계정에 저장하세요."},
  isms:{title:"ISMS/ISMS-P (국내 정보보호 관리체계)",summary:"국내 인터넷 서비스 제공자에게 의무화된 보안 인증입니다.",services:[{name:"CloudTrail + Config",role:"보안 이벤트 감사 로그 필수",connects:"→ ISMS 심사 시 증거 자료"},{name:"AWS Config Rules",role:"보안 설정 자동 준수 검사",connects:"→ 보안 위반 설정 자동 탐지"}],flow:"보안 정책 수립 → AWS 설정 → Config 자동 검사 → 위반 시 알림",tip:"AWS Well-Architected Framework 보안 지침 기반으로 아키텍처 문서를 준비하세요."},
  ptb:{title:"PCI DSS (카드 결제 보안 표준)",summary:"신용카드 결제 데이터를 처리하는 서비스라면 반드시 준수해야 하는 국제 표준입니다.",services:[{name:"격리 서브넷 + WAF",role:"카드 데이터 환경(CDE) 완전 격리",connects:"→ 결제 관련 서버만 별도 서브넷"},{name:"KMS 암호화",role:"카드 데이터 저장·전송 암호화",connects:"→ AES-256 + TLS 1.2 이상 필수"}],flow:"카드 결제 → TLS 암호화 전송 → CDE 격리 → KMS 암호화 저장",tip:"카드 번호를 직접 저장하지 말고 토크나이제이션을 사용하면 PCI DSS 범위를 크게 줄일 수 있습니다."},
  basic:{title:"기본 암호화",summary:"AWS 기본 암호화를 적용합니다. 추가 비용 없이 최소한의 보안을 확보합니다.",services:[{name:"AWS Managed KMS Key",role:"RDS·S3·EBS 기본 암호화",connects:"→ 별도 관리 없이 자동 암호화"},{name:"TLS 1.2 ACM",role:"데이터 전송 암호화",connects:"→ HTTPS 통신 보장"}],flow:"데이터 → AWS 자동 암호화 저장 → HTTPS로 전송",tip:"AWS Managed Key는 무료입니다. 추가 비용 없이 기본 암호화를 모든 서비스에 적용하세요."},
  strict:{title:"엄격한 암호화 (고객 관리형 키)",summary:"고객이 암호화 키를 직접 관리합니다. 금융·의료·공공 서비스 수준의 보안입니다.",services:[{name:"AWS KMS CMK",role:"암호화 키 고객이 직접 관리·교체·감사",connects:"→ CloudTrail로 키 사용 이력 추적"},{name:"AWS CloudHSM",role:"전용 하드웨어 키 관리 모듈",connects:"→ FIPS 140-2 Level 3 준수"}],flow:"데이터 → CMK로 암호화 → 저장 → 복호화 시 CloudTrail 기록",tip:"CMK는 월 1달러/키입니다. 서비스 단위로 키를 분리해 접근 제어를 세밀하게 하세요."},
  standard:{title:"표준 네트워크 격리 (2계층)",summary:"퍼블릭·프라이빗 서브넷으로 나누어 인터넷에 직접 노출되는 서버를 최소화합니다.",services:[{name:"퍼블릭 서브넷",role:"ALB·NAT GW만 위치 서버는 없음",connects:"→ 인터넷과 직접 통신하는 최소 자원만"},{name:"프라이빗 서브넷",role:"실제 앱 서버 위치",connects:"→ NAT GW를 통해서만 인터넷 접근"}],flow:"인터넷 → ALB(퍼블릭) → 앱(프라이빗) → DB",tip:"앱 서버는 반드시 프라이빗 서브넷에 두세요. 퍼블릭 서브넷에 서버를 두면 직접 공격 대상이 됩니다."},
  private:{title:"완전 격리 네트워크",summary:"인터넷과 완전히 차단된 네트워크. 사내망 또는 전용선으로만 접근 가능합니다.",services:[{name:"VPC 프라이빗 서브넷",role:"인터넷 접근 완전 차단",connects:"→ VPN 또는 Direct Connect로만 접근"},{name:"VPC Endpoint",role:"인터넷 없이 AWS 서비스 접근",connects:"→ S3·DynamoDB·ECR 내부 네트워크로 통신"}],flow:"사내 네트워크 → VPN/DX → VPC 프라이빗 → 서비스",tip:"완전 격리 환경에서는 필요한 모든 VPC Endpoint를 사전에 목록화하세요."},
  lt1min:{title:"RTO 1분 미만 (거의 즉시 복구)",summary:"장애 발생 후 1분 안에 서비스가 복구되어야 합니다. 금융·결제 수준입니다.",services:[{name:"Multi-AZ 자동 페일오버",role:"30초 내 DB 자동 전환",connects:"→ 인간 개입 없이 자동 복구"},{name:"ECS 헬스체크 + 자동 재시작",role:"컨테이너 장애 즉시 재시작",connects:"→ ALB가 정상 컨테이너로 자동 라우팅"}],flow:"장애 감지(10초) → 자동 복구(30초) → 서비스 정상화(1분 이내)",tip:"1분 이내 RTO는 모든 복구가 자동화되어야만 달성 가능합니다."},
  lt10min:{title:"RTO 10분 미만",summary:"10분 안에 복구. 대부분의 운영 서비스에서 현실적인 목표입니다.",services:[{name:"Auto Scaling + Multi-AZ",role:"주요 장애 자동 복구",connects:"→ 단일 서버·AZ 장애 자동 대응"},{name:"CloudWatch Alarm",role:"장애 즉시 담당자 알림",connects:"→ SNS → SMS/이메일/PagerDuty"}],flow:"장애 발생 → CloudWatch 감지(1분) → 알림 → 자동/수동 복구(10분 이내)",tip:"10분 RTO 달성을 위해 RunBook(복구 절차서)을 미리 작성하고 정기 훈련을 하세요."},
  minutes:{title:"RTO 수십 분",summary:"30분~1시간 내 복구. 비핵심 서비스나 내부 도구 수준의 요구사항입니다.",services:[{name:"CloudWatch + 수동 복구",role:"알림 → 담당자 확인 → 복구",connects:"→ 반자동 복구 프로세스"}],flow:"장애 → 알림 → 담당자 확인 → 수동 복구",tip:"수십 분 RTO라도 복구 절차를 문서화해두면 실제 장애 시 혼란을 크게 줄일 수 있습니다."},
  hours:{title:"RTO 수 시간",summary:"몇 시간 내 복구. 야간·주말 장애가 다음날 업무시간에 복구되어도 괜찮은 수준입니다.",services:[{name:"스냅샷 복구",role:"백업에서 서버 재생성",connects:"→ RDS 스냅샷 → 새 인스턴스 생성"}],flow:"장애 → 백업 확인 → 새 서버 생성 → 스냅샷 복구",tip:"수 시간 RTO라면 정기 스냅샷과 복구 테스트가 핵심입니다."},
  zero:{title:"RPO 0 (데이터 손실 없음)",summary:"장애가 나도 데이터가 단 1건도 손실되면 안 됩니다. 금융 트랜잭션 수준입니다.",services:[{name:"Aurora 동기 복제",role:"쓰기와 동시에 복사본 저장",connects:"→ 복사 완료 후 쓰기 확정"},{name:"SQS FIFO + 재전송",role:"메시지 손실 없는 전달",connects:"→ 수신 확인 전까지 재전송"}],flow:"데이터 입력 → 동시 복제 → 복제 완료 후 응답",tip:"RPO 0은 동기 복제가 필수입니다. 응답 속도가 약간 느려지는 트레이드오프가 있습니다."},
  single:{title:"단일 리전 (서울)",summary:"서울 리전 하나에만 서비스를 운영합니다. 국내 서비스의 일반적인 시작점입니다.",services:[{name:"서울 리전 3개 AZ",role:"국내 최저 지연시간 보장",connects:"→ 국내 사용자에게 최적 속도"}],flow:"국내 사용자 → 서울 리전 → 서비스",tip:"서울 리전은 국내 사용자에게 10~20ms의 낮은 지연시간을 제공합니다."},
  dr:{title:"DR 리전 (재해복구 대기)",summary:"주 리전(서울) 외에 DR 리전(일본·싱가포르)에 대기 인프라를 구성합니다.",services:[{name:"Aurora Global DB",role:"주 리전 데이터를 DR 리전에 복제 RPO 1초 미만",connects:"→ 리전 장애 시 수동 페일오버"},{name:"Route 53 Failover",role:"주 리전 장애 시 DR 리전으로 자동 전환",connects:"→ 전환 약 1~5분"},{name:"S3 Cross-Region Replication",role:"파일 데이터 DR 리전에 자동 복제",connects:"→ 파일 손실 방지"}],flow:"주 리전 장애 → Route 53 Failover → DR 리전으로 전환 → 서비스 지속",tip:"DR 훈련을 분기 1회 실시하세요. 테스트 안 한 DR은 실제 장애 시 작동하지 않을 수 있습니다."},
  active:{title:"멀티리전 Active-Active",summary:"여러 리전에서 동시에 서비스를 운영합니다. 글로벌 서비스나 최고 수준의 가용성이 필요한 경우입니다.",services:[{name:"Aurora Global DB",role:"여러 리전에서 동시 읽기·쓰기",connects:"→ 최저 레이턴시 + 리전 장애 자동 복구"},{name:"DynamoDB Global Tables",role:"멀티리전 양방향 자동 복제",connects:"→ NoSQL 글로벌 동기화"},{name:"Route 53 지연시간 라우팅",role:"사용자를 가장 가까운 리전으로 자동 연결",connects:"→ 글로벌 응답 속도 최적화"}],flow:"글로벌 사용자 → Route 53 가장 가까운 리전 → 해당 리전 서비스",tip:"Active-Active는 설계 복잡도가 매우 높습니다. 충돌 해결 정책을 사전에 반드시 설계하세요."},
  org:{title:"AWS Organizations (다중 계정 조직 관리)",summary:"여러 AWS 계정을 하나의 조직으로 묶어 중앙에서 관리합니다.",services:[{name:"조직 루트 계정",role:"전체 계정 정책 관리",connects:"→ SCP로 모든 멤버 계정에 정책 강제"},{name:"BU별 멤버 계정",role:"사업부·환경별 계정 분리",connects:"→ 계정 간 리소스 완전 격리"},{name:"통합 청구",role:"모든 계정 비용 한 곳에서 관리",connects:"→ 볼륨 할인 자동 적용"}],flow:"루트 계정(정책) → BU 계정 → 서비스 계정 → 리소스",tip:"Organizations와 Control Tower를 함께 쓰면 새 계정 생성과 보안 기준선 적용을 자동화할 수 있습니다."},
  envs:{title:"환경별 계정 분리 (Prod/Stage/Dev)",summary:"운영·스테이징·개발 환경을 각각 별도 AWS 계정으로 분리합니다.",services:[{name:"Prod 계정",role:"운영 환경 완전 격리",connects:"→ 개발자 실수로 운영 영향 차단"},{name:"Stage 계정",role:"운영과 동일한 환경에서 최종 테스트",connects:"→ 운영 배포 전 검증"},{name:"Dev 계정",role:"개발자 자유로운 실험 환경",connects:"→ 비용 낭비나 보안 사고 운영 영향 없음"}],flow:"개발 → Dev 계정 테스트 → Stage 계정 검증 → Prod 계정 배포",tip:"최소한 Prod 계정은 반드시 Dev와 분리하세요."},
  endpoint:{title:"VPC Endpoint (인터넷 없이 AWS 서비스 접근)",summary:"NAT GW 없이 AWS 서비스에 AWS 내부 네트워크로 직접 접근합니다. NAT GW 비용을 크게 줄일 수 있습니다.",services:[{name:"S3 Gateway Endpoint",role:"S3 접근에 NAT GW 비용 없음",connects:"→ 무료로 제공 즉시 절약"},{name:"Interface Endpoint",role:"ECR·Secrets Manager 등 접근",connects:"→ AZ당 소액 추가"}],flow:"프라이빗 서브넷 → VPC Endpoint → AWS 서비스 인터넷 통과 없음",tip:"S3와 DynamoDB는 무료 Gateway Endpoint가 있습니다. 설정만 해도 NAT GW 비용이 크게 줄어듭니다."},
  vpn:{title:"AWS Site-to-Site VPN",summary:"사무실·데이터센터와 AWS VPC를 인터넷을 통해 암호화된 터널로 연결합니다.",services:[{name:"Virtual Private Gateway",role:"AWS 측 VPN 엔드포인트",connects:"→ VPC에 연결"},{name:"Customer Gateway",role:"사무실 측 VPN 장비",connects:"→ 인터넷 공인 IP 필요"},{name:"IPSec 터널",role:"인터넷 구간 암호화 통신",connects:"→ AES-256 암호화"}],flow:"사무실 → 인터넷(암호화) → VPN 터널 → AWS VPC",tip:"VPN은 인터넷을 사용하므로 안정성이 낮습니다. 안정적인 연결이 필요하면 Direct Connect를 고려하세요."},
  dx:{title:"AWS Direct Connect (전용선 연결)",summary:"인터넷을 거치지 않고 사무실·데이터센터와 AWS를 물리적 전용선으로 연결합니다.",services:[{name:"전용 물리 회선",role:"인터넷 거치지 않는 안정적 연결",connects:"→ 지연시간 일정·대역폭 보장"},{name:"1Gbps / 10Gbps",role:"대용량 데이터 전송에 적합",connects:"→ 온프레미스 대규모 데이터 이동"}],flow:"사무실 → 물리 회선 → Direct Connect 위치 → AWS VPC",tip:"DX는 설치에 수주~수개월이 걸립니다. 긴급한 경우 VPN으로 먼저 연결하고 DX는 병행 준비하세요."},
  both:{title:"VPN + Direct Connect 혼합",summary:"Direct Connect를 주 연결로 쓰고 장애 시 VPN이 자동으로 백업 연결을 담당합니다.",services:[{name:"Direct Connect",role:"주 연결 - 안정적·고성능",connects:"→ 평상시 메인 경로"},{name:"VPN 백업",role:"DX 장애 시 자동 전환",connects:"→ 서비스 연속성 보장"}],flow:"DX(주) → DX 장애 시 자동 VPN으로 전환 → 서비스 지속",tip:"DX + VPN 백업 구성이 온프레미스 연결의 가장 안정적인 패턴입니다."},
  per_az:{title:"NAT GW AZ별 독립 구성",summary:"각 AZ에 NAT GW를 따로 둡니다. AZ 장애 시 다른 AZ가 영향을 받지 않습니다.",services:[{name:"NAT GW AZ-A",role:"AZ-A 전용 인터넷 출구",connects:"→ AZ-A 장애 시 AZ-B 영향 없음"},{name:"NAT GW AZ-B",role:"AZ-B 전용 인터넷 출구",connects:"→ AZ별 독립 운영"}],flow:"프라이빗 서버 → 같은 AZ의 NAT GW → 인터넷",tip:"운영 서비스에는 AZ별 NAT GW를 권장합니다."},
  shared:{title:"NAT GW 공유 (비용 절감)",summary:"하나의 NAT GW를 여러 AZ가 함께 사용합니다.",services:[{name:"NAT GW 1개",role:"AZ 구분 없이 모든 서버가 공유",connects:"→ NAT GW 비용 절반으로 절감"}],flow:"모든 프라이빗 서버 → 단일 NAT GW → 인터넷",tip:"개발 환경이나 비용이 중요한 경우에 적합합니다. 운영 환경에서는 AZ별 NAT GW를 권장합니다."},
  container:{title:"컨테이너 아키텍처",summary:"앱을 도커(Docker) 컨테이너로 패키징해 AWS에서 실행합니다. 현재 가장 대중적인 방식입니다.",services:[{name:"Docker 컨테이너",role:"앱과 환경을 하나로 패키징",connects:"→ 어디서나 동일하게 실행"},{name:"ECS / EKS",role:"컨테이너 자동 관리",connects:"→ 여러 컨테이너를 자동으로 배포·확장"},{name:"ECR",role:"컨테이너 이미지 저장소",connects:"→ 빌드한 이미지를 저장·관리"}],flow:"코드 → Docker 빌드 → ECR 저장 → ECS/EKS 배포 → 서비스",tip:"컨테이너는 개발 환경과 운영 환경이 동일해 내 PC에서는 되는데 문제를 없애줍니다."},
  vm:{title:"VM (가상 서버 EC2)",summary:"EC2라는 가상 서버를 직접 빌려 OS부터 앱까지 직접 관리합니다.",services:[{name:"EC2 인스턴스",role:"필요한 CPU·메모리의 가상 서버 임대",connects:"→ 시간당 과금"},{name:"Auto Scaling Group",role:"서버 수 자동 조절",connects:"→ CPU 높아지면 서버 자동 추가"}],flow:"요청 → ALB → EC2 클러스터 → RDS",tip:"특별한 이유가 없다면 ECS Fargate를 먼저 고려하세요. VM은 OS 패치·보안 설정 등을 직접 관리해야 합니다."},
  hybrid:{title:"혼합 아키텍처 (서버리스 + 컨테이너)",summary:"서비스별로 가장 적합한 방식을 섞어 씁니다.",services:[{name:"ECS Fargate",role:"메인 API 서버",connects:"→ 안정적·예측 가능한 트래픽 처리"},{name:"Lambda",role:"이벤트성·간헐적 작업",connects:"→ 이미지 처리·알림 발송 등"}],flow:"사용자 API → ECS / 이벤트 처리 → Lambda",tip:"혼합 아키텍처는 비용과 성능을 함께 최적화할 수 있지만 관리 복잡도가 높아집니다."},
  ec2_node:{title:"EC2 노드 직접 관리",summary:"ECS/EKS에서 실행하는 컨테이너의 서버를 EC2로 직접 관리합니다.",services:[{name:"EC2 Auto Scaling Group",role:"서버 증감 자동화",connects:"→ 수요에 맞게 자동 추가·제거"},{name:"Spot 인스턴스 혼합",role:"저렴한 빈 서버 활용",connects:"→ 비용 70% 절감 가능"}],flow:"서버(EC2) 관리 → ECS/EKS가 위에서 컨테이너 배치 → 앱 실행",tip:"대규모 서비스에서 EC2 노드를 쓰면 Fargate 대비 40~60% 비용 절감이 가능합니다."},
  ecs_asg:{title:"CPU/메모리 기준 자동 확장 (기본)",summary:"서버가 바빠지면 자동으로 서버를 추가하는 기본 확장 방식입니다.",services:[{name:"ECS Service Auto Scaling",role:"CPU 70% 초과 시 Task 자동 추가",connects:"→ 트래픽 증가 자동 대응"},{name:"Target Tracking Policy",role:"목표 수치 유지",connects:"→ CPU를 항상 60~70%로 유지"}],flow:"트래픽 증가 → CPU 상승 → Auto Scaling 트리거 → 새 컨테이너 추가",tip:"스케일 아웃은 빠르게(2분), 스케일 인은 천천히(15분) 설정하는 것이 안전합니다."},
  scheduled:{title:"스케줄 사전 확장",summary:"이벤트 시작 전 미리 서버를 늘려놓는 방식입니다.",services:[{name:"Scheduled Scaling",role:"특정 시각에 서버 수를 미리 설정",connects:"→ 이벤트 전 미리 준비"}],flow:"이벤트 10분 전 서버 자동 확장 → 트래픽 폭증 수용 → 이벤트 후 자동 축소",tip:"스케줄 확장은 가장 확실한 스파이크 대비책입니다."},
  manual:{title:"수동 용량 조절",summary:"자동 확장 없이 수동으로 서버 수를 조정합니다.",services:[{name:"고정 ECS Task 수",role:"항상 동일한 수의 컨테이너 실행",connects:"→ 예측 가능한 비용"}],flow:"고정된 수의 서버 → 일정한 처리 → 변화 없음",tip:"수동 조절을 선택했어도 최소한 CPU·메모리 알람은 설정해두세요."},
  keda:{title:"KEDA (대기열 메시지 수 기준 확장)",summary:"SQS·Kinesis 등 대기열에 쌓인 메시지 수에 따라 자동으로 서버를 늘리고 줄입니다.",services:[{name:"KEDA ScaledObject",role:"메시지 수 목표치 설정",connects:"→ 큐 길이에 따라 Pod 자동 증감"},{name:"SQS 모니터링",role:"메시지 수 실시간 감지",connects:"→ 메시지 0개면 Pod 0개까지 축소"}],flow:"SQS에 메시지 쌓임 → KEDA 감지 → Pod 자동 추가 → 메시지 처리 → Pod 자동 축소",tip:"minReplicaCount=0 설정으로 메시지가 없을 때 Pod를 완전히 없애 비용을 최소화할 수 있습니다."},
  aurora_mysql:{title:"Aurora MySQL",summary:"AWS가 최적화한 MySQL 호환 DB입니다. 일반 MySQL보다 5배 빠르고 관리가 자동화됩니다.",services:[{name:"Aurora 스토리지",role:"6개 복사본 자동 유지",connects:"→ 데이터 손실 가능성 극히 낮음"},{name:"자동 페일오버",role:"Primary 장애 시 30초 내 자동 전환",connects:"→ 수동 개입 불필요"}],flow:"앱 → Aurora MySQL (Primary) → 읽기는 Read Replica",tip:"기존에 MySQL을 쓰고 있다면 Aurora MySQL로 마이그레이션이 가장 쉽습니다."},
  rds_mysql:{title:"RDS MySQL",summary:"AWS가 관리하는 표준 MySQL입니다. 패치·백업을 AWS가 자동 처리합니다.",services:[{name:"RDS 인스턴스",role:"표준 MySQL 서버",connects:"→ 일반적인 사용에 충분"},{name:"자동 백업",role:"매일 자동 스냅샷",connects:"→ 35일 이내 복구 가능"},{name:"Multi-AZ",role:"장애 시 자동 전환 옵션",connects:"→ 운영 환경에서는 필수"}],flow:"앱 → RDS MySQL → 자동 백업 → S3",tip:"대규모 성장이 예상된다면 Aurora MySQL로 시작하는 것을 고려하세요."},
  rds_pg:{title:"RDS PostgreSQL",summary:"AWS가 관리하는 표준 PostgreSQL입니다. JSON·지리 데이터·복잡한 쿼리에 강합니다.",services:[{name:"RDS 인스턴스",role:"표준 PostgreSQL 서버",connects:"→ 복잡한 쿼리·JSON 데이터에 적합"},{name:"확장 타입",role:"PostGIS(지리정보)·pgvector(AI임베딩) 등",connects:"→ 특수 용도 확장 지원"}],flow:"앱 → RDS PostgreSQL → 복잡한 쿼리 처리 → 결과 반환",tip:"pgvector 확장으로 AI 임베딩 벡터를 PostgreSQL에 직접 저장·검색할 수 있습니다."},
  multi_az:{title:"Multi-AZ 자동 페일오버",summary:"DB 서버를 2개 이상의 AZ에 동시에 운영하고 하나가 죽으면 자동으로 전환합니다.",services:[{name:"Primary DB",role:"주 DB 서버",connects:"→ 정상 운영 중"},{name:"Standby DB",role:"대기 중인 복제본 (다른 AZ)",connects:"→ Primary 장애 시 30초 내 자동 전환"}],flow:"Primary 장애 → AWS 자동 감지(15초) → Standby 승격(30초) → 서비스 재개",tip:"운영 서비스 DB에는 Multi-AZ가 필수입니다. DB 단일 장애점을 제거합니다."},
  multi_az_read:{title:"Multi-AZ + Read Replica",summary:"Multi-AZ 자동 복구에 더해 읽기 트래픽을 별도 서버로 분산해 성능을 높입니다.",services:[{name:"Multi-AZ",role:"장애 대비 자동 전환",connects:"→ 가용성 확보"},{name:"Read Replica",role:"조회 요청 전담 서버",connects:"→ Primary DB 부하 40~60% 감소"}],flow:"SELECT 쿼리 → Read Replica / INSERT·UPDATE → Primary",tip:"읽기가 전체 쿼리의 70% 이상인 서비스에서 Read Replica 추가 시 DB 병목을 크게 완화할 수 있습니다."},
  single_az:{title:"Single-AZ (개발·비용 절감용)",summary:"DB 서버를 1개만 운영합니다. 장애 시 수동으로 복구해야 합니다.",services:[{name:"단일 RDS 인스턴스",role:"1개 서버만 운영",connects:"→ 장애 시 수동 재시작 필요"}],flow:"DB 서버(1개) → 장애 시 수동 복구",tip:"운영 서비스에는 사용하지 마세요."},
  global:{title:"Global DB / 멀티리전",summary:"DB 데이터를 여러 리전에 실시간으로 복제합니다.",services:[{name:"Aurora Global Database",role:"리전 간 1초 미만 복제",connects:"→ 리전 장애 시 수동 페일오버"},{name:"보조 리전 Read Endpoint",role:"보조 리전에서 읽기 처리",connects:"→ 글로벌 사용자 지연시간 감소"}],flow:"서울(Primary) → 실시간 복제 → 도쿄(Secondary) → 서울 장애 시 도쿄로 전환",tip:"글로벌 DB는 비용이 크게 올라갑니다. 리전 전체 장애가 비즈니스에 치명적인지 먼저 판단하세요."},
  dax:{title:"DynamoDB Accelerator (DAX)",summary:"DynamoDB 앞에 붙이는 전용 캐시입니다. 코드 변경 없이 응답 속도를 마이크로초 단위로 줄입니다.",services:[{name:"DAX 클러스터",role:"DynamoDB 앞단 인메모리 캐시",connects:"→ 읽기 지연 1ms → 마이크로초"}],flow:"앱 → DAX 캐시 → 캐시 미스 시 DynamoDB",tip:"DynamoDB를 쓰는데 읽기 성능이 부족하다면 DAX가 가장 빠른 해결책입니다. 단 월 최소 100달러 이상의 추가 비용이 발생합니다."},
  db_search:{title:"DB 기본 검색 (LIKE 쿼리)",summary:"DB에서 포함된 키워드를 찾는 단순 검색입니다. 별도 검색 엔진 없이 구현 가능합니다.",services:[{name:"SQL LIKE 검색",role:"DB에서 직접 텍스트 검색",connects:"→ 데이터가 많아지면 성능 저하"}],flow:"검색어 → DB LIKE 쿼리 → 결과 반환",tip:"데이터가 수백만 건을 넘거나 한글 형태소 분석이 필요하면 OpenSearch로 전환을 고려하세요."},
  opensearch:{title:"Amazon OpenSearch Service",summary:"전문 검색 엔진입니다. 복잡한 검색·로그 분석·실시간 대시보드에 사용합니다.",services:[{name:"OpenSearch 클러스터",role:"전문 검색 인덱스",connects:"→ 한글 형태소·퍼지 검색·필터 지원"},{name:"Lambda Sink",role:"DB 변경사항을 OpenSearch에 자동 동기화",connects:"→ DB가 SoT OpenSearch는 검색 전용"}],flow:"데이터 변경 → Lambda → OpenSearch 인덱싱 → 검색 요청 → 조회",tip:"항상 DB를 Source of Truth로 두고 OpenSearch는 검색 전용으로 사용하세요."},
  efs:{title:"Amazon EFS (공유 파일 시스템)",summary:"여러 서버가 동시에 같은 파일을 읽고 쓸 수 있는 공유 폴더입니다.",services:[{name:"NFS 마운트",role:"여러 EC2/ECS가 동시 접근",connects:"→ 파일 시스템으로 마운트"},{name:"자동 확장",role:"용량 걱정 없이 자동 증가",connects:"→ 스토리지 프로비저닝 불필요"}],flow:"여러 서버 → EFS 마운트 → 파일 공유",tip:"EFS는 S3보다 비쌉니다. 여러 서버가 파일을 공유해야 할 때만 EFS를 쓰고 나머지는 S3를 사용하세요."},
  ebs:{title:"Amazon EBS (블록 스토리지)",summary:"EC2 서버에 연결되는 고성능 디스크입니다. DB 파일·OS 디스크 등에 사용합니다.",services:[{name:"gp3 볼륨",role:"범용 SSD 스토리지",connects:"→ 성능 조절 가능·비용 효율"},{name:"io2 볼륨",role:"고성능 SSD DB 전용",connects:"→ IOPS 64,000까지 지원"}],flow:"서버 → EBS 마운트 → 데이터 읽기/쓰기",tip:"EBS는 한 서버에만 연결할 수 있습니다. 여러 서버에서 공유하려면 EFS를 사용하세요."},
  cognito:{title:"Amazon Cognito",summary:"AWS가 제공하는 회원 가입·로그인 서비스입니다. 직접 구현하지 않아도 됩니다.",services:[{name:"User Pool",role:"회원 정보 저장·인증 처리",connects:"→ 회원 가입·비밀번호 찾기 자동"},{name:"소셜 로그인",role:"Google·Kakao·Apple 연동",connects:"→ 소셜 로그인 코드 없이 설정"}],flow:"사용자 → Cognito 인증 → JWT 발급 → API 호출",tip:"Cognito는 MAU 50,000명까지 무료입니다."},
  sso:{title:"SSO / 사내 IdP 연동",summary:"회사 구글 계정·Azure AD·Okta 같은 사내 계정으로 로그인합니다.",services:[{name:"SAML 2.0 / OIDC",role:"표준 프로토콜로 사내 IdP와 연동",connects:"→ 기존 계정 재사용"}],flow:"사용자 → 사내 계정 → SAML → 앱 → 로그인 완료",tip:"B2B SaaS나 사내 도구에서는 SSO가 필수입니다."},
  selfmgd:{title:"자체 인증 서버 직접 구현",summary:"JWT를 직접 발급·검증하는 인증 서버를 만들어 운영합니다.",services:[{name:"JWT 발급 서버",role:"로그인 → Access Token + Refresh Token 발급",connects:"→ Authorization 헤더에 포함"},{name:"Redis 세션 관리",role:"토큰 블랙리스트·리프레시 토큰 관리",connects:"→ 로그아웃 즉시 처리"}],flow:"로그인 → JWT 발급 → API 요청마다 토큰 검증",tip:"직접 인증 서버를 만들면 보안 취약점 관리를 모두 직접 책임져야 합니다. Cognito를 먼저 검토하세요."},
  sync_only:{title:"동기 처리만",summary:"요청하면 즉시 처리하고 바로 응답을 줍니다. 가장 단순한 방식입니다.",services:[{name:"ALB",role:"트래픽 분산",connects:"→ 서버로 요청 전달"},{name:"ECS/Lambda",role:"즉시 처리 후 응답",connects:"→ 처리 완료까지 연결 유지"}],flow:"사용자 요청 → 서버가 처리 → 즉시 응답",tip:"시간이 오래 걸리는 작업은 비동기로 분리하는 것을 고려하세요."},
  async:{title:"비동기 처리만",summary:"요청을 받으면 큐에 쌓아두고 나중에 처리합니다. 서버가 바빠도 요청이 유실되지 않습니다.",services:[{name:"SQS",role:"처리할 일을 줄 세우는 대기열",connects:"→ 서버가 처리할 수 있는 만큼만 가져감"},{name:"Lambda / ECS Worker",role:"큐에서 가져와 처리",connects:"→ 처리 완료 후 삭제"},{name:"DLQ",role:"처리 실패한 메시지 별도 보관",connects:"→ 실패 원인 분석·재처리"}],flow:"사용자 요청 → SQS 대기열 → Worker가 처리 → 처리 완료",tip:"처리 완료를 알려주는 방법(폴링·이메일 알림)을 함께 설계하세요."},
  mixed:{title:"혼합 처리 (동기 + 비동기)",summary:"즉시 응답이 필요한 건 동기로 후처리는 비동기로 나눠서 처리합니다.",services:[{name:"동기 처리",role:"즉시 결과가 필요한 핵심 처리",connects:"→ 성공/실패를 즉시 반환"},{name:"비동기 처리",role:"즉시 응답 불필요한 후처리",connects:"→ SQS에 쌓아두고 나중에 처리"}],flow:"주문 확인(동기) → 즉시 응답 → SQS에 이벤트 발행 → Lambda가 이메일 발송(비동기)",tip:"대부분의 복잡한 서비스가 이 방식을 씁니다."},
  msk:{title:"Amazon MSK (Managed Kafka)",summary:"Kafka를 AWS에서 완전 관리형으로 제공합니다. 초당 수십만 건의 이벤트를 처리하는 대규모 스트리밍에 사용합니다.",services:[{name:"Kafka 브로커 클러스터",role:"고처리량 메시지 브로커",connects:"→ 초당 수십만 건 처리"},{name:"컨슈머 그룹",role:"여러 서비스가 같은 토픽을 독립적으로 소비",connects:"→ 각자 다른 처리"}],flow:"생산자 → Kafka 토픽 → 컨슈머 그룹 → 각 서비스 처리",tip:"MSK는 운영 복잡도가 높습니다. SQS/SNS로 해결 가능하다면 MSK는 과한 선택입니다."},
  alb:{title:"ALB (Application Load Balancer)",summary:"웹·앱 서비스의 표준 입구입니다. 들어오는 HTTP/HTTPS 트래픽을 여러 서버에 분산합니다.",services:[{name:"리스너",role:"80/443 포트에서 트래픽 수신",connects:"→ HTTP → HTTPS 자동 리다이렉트"},{name:"타겟 그룹",role:"트래픽을 받을 서버 그룹",connects:"→ ECS Task·EC2·Lambda 연결"},{name:"헬스체크",role:"비정상 서버로 트래픽 자동 차단",connects:"→ 장애 서버 자동 제외"}],flow:"사용자 → ALB → 헬스체크 통과한 서버로 분산 → 응답",tip:"ALB는 경로·헤더·쿼리 파라미터 기반으로 트래픽을 다르게 라우팅할 수 있습니다."},
  api_gateway:{title:"AWS API Gateway",summary:"Lambda 함수나 HTTP 엔드포인트 앞에 붙이는 AWS 완전 관리형 게이트웨이입니다.",services:[{name:"REST API / HTTP API",role:"HTTP 요청을 받아 Lambda 또는 서버로 전달",connects:"→ 요청 변환·응답 변환 가능"},{name:"Usage Plan + API Key",role:"파트너별 요청 수 제한·API 키 관리",connects:"→ 외부 개발자 API 접근 제어"}],flow:"클라이언트 → API Gateway → Lambda / ECS → DB",tip:"Lambda와 조합 시 완전 서버리스 API가 완성됩니다. ECS에 쓰면 ALB보다 비용이 높습니다."},
  nlb:{title:"NLB (Network Load Balancer)",summary:"TCP/UDP 레벨에서 트래픽을 분산합니다. 초저지연이 필요한 게임·IoT·실시간 서비스에 사용합니다.",services:[{name:"L4 로드밸런싱",role:"HTTP/HTTPS가 아닌 TCP/UDP 처리",connects:"→ 고성능·초저지연"},{name:"고정 IP",role:"NLB는 IP가 변하지 않음",connects:"→ 방화벽 화이트리스트 필요한 기업 고객에 유리"}],flow:"클라이언트 → NLB → 백엔드 서버",tip:"HTTP 서비스에는 ALB를 쓰세요. NLB는 게임 서버·IoT·gRPC 등 특수한 경우에 사용합니다."},
  geoloc:{title:"Route 53 지리적 라우팅",summary:"사용자의 위치에 따라 가장 가까운 서버로 연결합니다.",services:[{name:"지역별 레코드",role:"국가·대륙별 트래픽 라우팅",connects:"→ 한국 사용자는 서울 리전으로"},{name:"기본 레코드",role:"위치 정보 없는 경우 기본 서버",connects:"→ 전 세계 어디서나 접근"}],flow:"한국 사용자 → 서울 리전 / 미국 사용자 → 미국 리전",tip:"지리적 라우팅은 법적 데이터 거주 요건 준수에도 활용됩니다."},
  health:{title:"Route 53 장애 조치 라우팅",summary:"주 서버가 장애 나면 자동으로 DR 서버로 트래픽을 전환합니다.",services:[{name:"헬스체크",role:"30초마다 서버 상태 확인",connects:"→ 3번 연속 실패 시 장애로 판정"},{name:"Failover Secondary",role:"장애 시 자동 전환",connects:"→ DR 서버"}],flow:"Primary 장애 → Route 53 헬스체크 실패 → Secondary로 자동 전환",tip:"TTL을 60초로 낮게 설정해야 빠른 전환이 가능합니다."},
  step_functions:{title:"AWS Step Functions",summary:"여러 단계를 순서대로 실행하고 오류를 자동으로 처리하는 워크플로 서비스입니다.",services:[{name:"상태 머신",role:"각 단계와 전환 조건을 정의",connects:"→ 성공/실패/타임아웃별 다음 단계 지정"},{name:"재시도 + 보상 액션",role:"단계 실패 시 자동 재시도·전체 실패 시 보상 실행",connects:"→ Saga 패턴 구현"}],flow:"주문 접수 → 재고 확인 → 결제 → 배송 / 실패 시 → 환불 자동 실행",tip:"Standard 모드는 장기 실행에, Express 모드는 고빈도 단기 실행에 사용하세요."},
  aws_batch:{title:"AWS Batch (대용량 배치 처리)",summary:"수천 개의 컨테이너를 병렬로 실행하는 대용량 배치 작업에 사용합니다.",services:[{name:"Job Queue",role:"배치 작업을 줄 세우는 대기열",connects:"→ 우선순위 설정 가능"},{name:"Compute Environment",role:"Spot·On-Demand EC2 자동 프로비저닝",connects:"→ 작업 완료 후 서버 자동 반환"}],flow:"작업 제출 → Job Queue → Compute Environment 생성 → 병렬 실행 → 결과 S3 저장",tip:"Spot 인스턴스를 활용하면 On-Demand 대비 최대 90% 비용 절감이 가능합니다."},
  eventbridge_sch:{title:"EventBridge Scheduler (정기 스케줄 작업)",summary:"크론(Cron) 표현식으로 정기적으로 Lambda·ECS Task를 자동 실행합니다.",services:[{name:"Cron 표현식",role:"분·시간·일·월·요일 기반 스케줄",connects:"→ 매일 오전 9시 등"},{name:"타임존 지원",role:"특정 타임존 기준 스케줄",connects:"→ 서머타임 자동 처리"}],flow:"스케줄 트리거 → Lambda / ECS Task 자동 실행 → 완료",tip:"FlexibleTimeWindow를 사용하면 배치 호출이 분산되어 동시 폭증을 방지할 수 있습니다."},
  ecs_scheduled:{title:"ECS Scheduled Task (정기 컨테이너 실행)",summary:"EventBridge Scheduler가 정해진 시각에 ECS Task를 자동으로 실행합니다.",services:[{name:"EventBridge Scheduler",role:"스케줄 트리거",connects:"→ 매일·매시간·매주 등 설정"},{name:"ECS Task",role:"컨테이너를 일회성으로 실행",connects:"→ 완료 후 자동 종료"}],flow:"스케줄 시각 → ECS Task 실행 → 처리 완료 → 컨테이너 자동 종료",tip:"기존 컨테이너 코드를 그대로 재사용할 수 있습니다. 멱등성 설계가 필수입니다."},
  spring_boot:{title:"Java / Spring Boot",summary:"국내 기업의 60% 이상이 사용하는 엔터프라이즈 표준 프레임워크입니다.",services:[{name:"Spring MVC / WebFlux",role:"REST API 개발 표준",connects:"→ @Controller로 빠르게 개발"},{name:"Spring Data JPA",role:"DB 접근 추상화",connects:"→ SQL 없이 객체로 DB 조작"},{name:"Spring Security",role:"인증·인가 프레임워크",connects:"→ JWT·OAuth2·세션 모두 지원"}],flow:"요청 → Controller → Service → Repository → DB → 응답",tip:"Spring Boot는 최소 512MB RAM과 콜드스타트 1~3초가 필요합니다. Lambda보다 ECS/EKS에 더 적합합니다."},
  node_express:{title:"Node.js / Express·Fastify",summary:"JavaScript로 빠르게 API를 만들 수 있는 런타임입니다.",services:[{name:"Express.js",role:"가장 널리 쓰이는 Node.js 웹 프레임워크",connects:"→ 빠른 시작·풍부한 미들웨어 생태계"},{name:"Fastify",role:"Express보다 3배 빠른 고성능 프레임워크",connects:"→ 타입 안전성"}],flow:"요청 → Express 라우터 → 미들웨어 → 핸들러 → DB → 응답",tip:"Node.js는 I/O 집중적인 API 서버에 최적입니다."},
  python_fastapi:{title:"Python / FastAPI·Django",summary:"AI·ML 연동이 쉽고 개발 속도가 빠른 언어입니다.",services:[{name:"FastAPI",role:"자동 OpenAPI 문서 생성·비동기 처리",connects:"→ 빠른 성능"},{name:"Django",role:"All-in-One 프레임워크",connects:"→ 관리자 페이지·ORM 내장"},{name:"AI/ML 통합",role:"PyTorch·TensorFlow 직접 호출",connects:"→ ML 모델을 API로 즉시 서빙"}],flow:"요청 → FastAPI 라우터 → 비즈니스 로직 → DB → 응답",tip:"AI/ML 기능이 있거나 빠른 프로토타이핑이 필요하다면 Python + FastAPI가 최적입니다."},
  go:{title:"Go (Golang)",summary:"Google이 만든 컴파일 언어입니다. 컨테이너 이미지가 10MB 수준으로 작고 메모리 효율이 뛰어납니다.",services:[{name:"단일 바이너리 배포",role:"의존성 없는 정적 바이너리",connects:"→ 컨테이너 이미지 10~15MB"},{name:"Goroutine",role:"경량 동시성 처리",connects:"→ 수천 개 동시 요청 처리"}],flow:"요청 → Go HTTP 서버 → 비즈니스 로직 → DB → 응답",tip:"Go로 만든 컨테이너는 Spring Boot 대비 메모리 90% 절감이 가능합니다."},
  rust:{title:"Rust",summary:"메모리 안전성과 최고 성능을 동시에 제공하는 시스템 언어입니다.",services:[{name:"메모리 안전",role:"컴파일 타임에 메모리 오류 탐지",connects:"→ 런타임 크래시 없음"},{name:"Lambda 최적화",role:"거의 0ms 콜드스타트",connects:"→ Go보다도 빠른 시작"}],flow:"요청 → Rust HTTP 서버 → 처리 → 응답",tip:"Rust는 학습 곡선이 매우 높습니다. 팀 모두가 숙련되지 않으면 생산성이 크게 낮아질 수 있습니다."},
  aws_apigw:{title:"AWS API Gateway (관리형)",summary:"Lambda 함수나 HTTP 엔드포인트 앞에 붙이는 AWS 완전 관리형 게이트웨이입니다.",services:[{name:"REST API / HTTP API",role:"HTTP 요청을 받아 Lambda 또는 서버로 전달",connects:"→ 요청 변환·응답 변환 가능"},{name:"인증·인가",role:"Cognito·Lambda Authorizer 통합",connects:"→ API 키·JWT 토큰 자동 검증"}],flow:"클라이언트 → API Gateway → Lambda / ECS → DB",tip:"Lambda와 조합 시 완전 서버리스 API가 완성됩니다."},
  alb_only:{title:"ALB만 사용 (단순 컨테이너 구성)",summary:"API Gateway 없이 ALB가 바로 컨테이너로 트래픽을 전달합니다. 가장 단순하고 저렴합니다.",services:[{name:"ALB",role:"트래픽 분산 + 헬스체크",connects:"→ ECS Task로 직접 연결"}],flow:"클라이언트 → ALB → ECS 컨테이너 → DB",tip:"컨테이너 서비스에서는 ALB가 API Gateway보다 비용이 훨씬 저렴합니다."},
  spring_gateway:{title:"Spring Cloud Gateway",summary:"Spring Boot 팀에서 자연스럽게 선택하는 API 게이트웨이입니다.",services:[{name:"라우팅 설정",role:"Java 코드로 라우팅 규칙 정의",connects:"→ 코드 기반 관리·버전 관리 가능"},{name:"Resilience4j",role:"서킷브레이커 내장",connects:"→ 다운스트림 서비스 장애 시 자동 차단"}],flow:"클라이언트 → Spring Gateway → 서비스별 라우팅 → 각 마이크로서비스",tip:"Spring Boot 팀이라면 별도 기술 학습 없이 바로 사용 가능합니다."},
  kong:{title:"Kong Gateway",summary:"100개 이상의 플러그인을 가진 강력한 API 게이트웨이입니다.",services:[{name:"플러그인 시스템",role:"인증·속도제한·변환·로깅을 코드 없이 설정",connects:"→ declarative 설정으로 정책 관리"},{name:"Kong DB-less 모드",role:"YAML 파일로 설정 관리",connects:"→ 설정이 코드로 버전 관리"}],flow:"클라이언트 → Kong → 플러그인 체인 → 서비스 → DB",tip:"Kong은 PostgreSQL RDS가 필요합니다."},
  rest:{title:"REST / HTTP+JSON (범용 표준)",summary:"가장 널리 쓰이는 API 통신 방식입니다. 브라우저·모바일·서드파티 연동이 가장 쉽습니다.",services:[{name:"HTTP 메서드",role:"GET(조회)·POST(생성)·PUT(수정)·DELETE(삭제)",connects:"→ 직관적인 리소스 기반 API 설계"},{name:"JSON",role:"사람이 읽기 쉬운 데이터 형식",connects:"→ 모든 언어에서 파싱 가능"},{name:"Swagger/OpenAPI",role:"API 문서 자동 생성",connects:"→ 개발자 포털·클라이언트 코드 자동 생성"}],flow:"클라이언트 → HTTPS + JSON → 서버 → 처리 → JSON 응답",tip:"REST는 가장 범용적인 선택입니다. 특별한 이유가 없다면 REST를 먼저 고려하세요."},
  grpc:{title:"gRPC (고성능 바이너리 통신)",summary:"Protocol Buffers 스키마로 타입을 강제하고 HTTP/2로 고속 통신합니다.",services:[{name:"Protobuf",role:"바이너리 직렬화",connects:"→ JSON 대비 메시지 크기 60~70% 절감"},{name:"HTTP/2 멀티플렉싱",role:"하나의 연결로 여러 요청 동시 처리",connects:"→ REST보다 5~10배 빠른 내부 통신"}],flow:"클라이언트 → gRPC 스텁 → HTTP/2 → gRPC 서버 → 응답",tip:"gRPC는 ALB에서 HTTP/2 리스너를 활성화해야 합니다."},
  graphql:{title:"GraphQL (클라이언트 주도 쿼리)",summary:"클라이언트가 필요한 데이터만 골라서 요청합니다. 과다 조회·부족 조회 문제를 해결합니다.",services:[{name:"단일 엔드포인트",role:"모든 요청이 /graphql 하나로",connects:"→ REST의 수백 개 엔드포인트 대신"},{name:"DataLoader 패턴",role:"N+1 쿼리 문제 해결 필수",connects:"→ 반드시 DataLoader 적용"}],flow:"클라이언트 → GraphQL 쿼리 → Resolver → DB → 필요한 데이터만 반환",tip:"GraphQL은 모바일 앱이나 복잡한 대시보드처럼 다양한 데이터를 유연하게 조합해야 할 때 빛을 발합니다."},
  k8s_dns:{title:"K8s 내장 DNS (CoreDNS)",summary:"EKS를 쓰면 자동으로 제공되는 서비스 디스커버리입니다. 설정 없이 서비스 이름으로 통신합니다.",services:[{name:"CoreDNS",role:"K8s 클러스터 내 DNS 서버",connects:"→ 자동 설치·관리 불필요"},{name:"서비스명으로 통신",role:"service-name.namespace.svc.cluster.local",connects:"→ IP 주소 없이 이름으로 호출"}],flow:"Pod → 서비스명으로 요청 → CoreDNS 조회 → 대상 Pod IP → 통신",tip:"EKS를 쓰면 CoreDNS가 자동으로 설치됩니다. 별도 서비스 디스커버리 도구가 필요 없습니다."},
  cloud_map:{title:"AWS Cloud Map (서비스 디스커버리)",summary:"ECS·Lambda·EC2가 혼합된 환경에서 서비스를 이름으로 찾아줍니다.",services:[{name:"서비스 레지스트리",role:"서비스 이름 → IP:포트 매핑 자동 등록",connects:"→ 컨테이너 시작/중지 시 자동 업데이트"},{name:"ECS Service Connect",role:"ECS 서비스 간 자동 디스커버리",connects:"→ Cloud Map 기반·추가 설정 불필요"}],flow:"서비스 A → Cloud Map 조회 → 서비스 B의 현재 IP:포트 → 직접 연결",tip:"ECS + ECS Service Connect 조합이면 Cloud Map이 자동으로 설정됩니다."},
  eureka:{title:"Spring Cloud Eureka",summary:"Spring Boot 생태계의 전통적인 서비스 레지스트리입니다.",services:[{name:"Eureka 서버",role:"서비스 등록·조회 API 제공",connects:"→ 별도 ECS 서비스로 항상 실행 필요"}],flow:"서비스 시작 → Eureka에 자동 등록 → 다른 서비스가 Eureka 조회 → 통신",tip:"신규 프로젝트라면 Eureka 대신 AWS Cloud Map + ECS Service Connect 조합을 먼저 고려하세요."},
  yes:{title:"사용 / 활성화",summary:"이 기능을 사용합니다.",services:[{name:"해당 서비스·기능 활성화",role:"활성화",connects:"→ 선택한 설정 적용"}],flow:"기능 활성화 → 서비스에 적용",tip:"추가 기능을 활성화하면 비용이 증가할 수 있습니다. AWS Pricing Calculator로 미리 확인하세요."},
  no:{title:"사용 안 함 / 해당 없음",summary:"이 기능을 사용하지 않습니다.",services:[{name:"기본 설정 유지",role:"현재 설정 그대로 사용",connects:"→ 추후 필요 시 언제든 추가 가능"}],flow:"기존 구성 → 변경 없음",tip:"필요 없는 기능을 억지로 추가하면 복잡도만 올라갑니다."},
  none:{title:"없음 / 해당 없음",summary:"이 항목을 사용하지 않습니다.",services:[{name:"기본 설정 유지",role:"현재 설정 그대로 사용",connects:"→ 추후 필요 시 언제든 추가 가능"}],flow:"기존 구성 → 변경 없음",tip:"필요 없는 기능을 억지로 추가하면 복잡도만 올라갑니다."},
  basic_waf:{title:"AWS WAF 기본 규칙",summary:"일반적인 웹 공격(SQL 주입·XSS·봇)으로부터 서비스를 보호합니다.",services:[{name:"AWS Managed Rules",role:"OWASP Top 10 공격 자동 차단",connects:"→ SQL Injection·XSS 등"},{name:"속도 기반 규칙",role:"같은 IP에서 5분에 2000건 초과 시 차단",connects:"→ 기본적인 DDoS 방어"}],flow:"트래픽 → WAF 검사 → 악성 요청 차단 / 정상 요청 → 서버",tip:"CloudFront 또는 ALB 앞에 연결합니다. 월 5달러 + 처리량 기준으로 가장 저렴한 보안 레이어입니다."},
  bot:{title:"WAF Bot Control (봇 관리)",summary:"매크로·크롤러·스크래퍼를 정밀하게 탐지하고 차단합니다.",services:[{name:"봇 탐지",role:"알려진 봇 자동 분류",connects:"→ 검색엔진 봇은 허용·악성 봇은 차단"},{name:"챌린지 기반 검증",role:"의심스러운 요청에 CAPTCHA 자동 발생",connects:"→ 자동화 봇은 통과 불가"}],flow:"트래픽 → Bot Control → 봇 분류 → 허용/차단/챌린지",tip:"티켓팅·한정판 판매 서비스에서 Bot Control 없이 이벤트를 열면 매크로가 모든 재고를 쓸어갑니다."},
  shield:{title:"AWS Shield Advanced (DDoS 방어)",summary:"대규모 DDoS 공격으로부터 인프라를 보호합니다.",services:[{name:"DDoS 자동 완화",role:"공격 감지 즉시 자동 트래픽 필터링",connects:"→ 서비스 중단 없이 공격 흡수"},{name:"DDoS 비용 보호",role:"공격으로 인한 Auto Scaling 비용 환급",connects:"→ 공격 시 스케일아웃 비용 청구 없음"}],flow:"대규모 공격 트래픽 → Shield 자동 필터링 → 정상 트래픽만 서버로 → 서비스 지속",tip:"Shield Advanced는 월 3,000달러로 비쌉니다. DAU 100만 이상의 서비스에서 검토하세요."},
  terraform:{title:"Terraform (인프라 코드 관리)",summary:"인프라를 코드(HCL 언어)로 선언하고 자동으로 생성·변경·삭제합니다.",services:[{name:"HCL 코드",role:"원하는 인프라 상태를 선언",connects:"→ terraform apply 한 번에 모든 리소스 생성"},{name:"상태 파일 tfstate",role:"현재 인프라 상태 추적",connects:"→ 변경 사항만 정확히 업데이트"}],flow:"코드 작성 → terraform plan(미리보기) → terraform apply(적용) → 인프라 생성",tip:"Terraform은 AWS 외에 다른 클라우드도 함께 관리할 수 있는 멀티클라우드 도구입니다."},
  cdk:{title:"AWS CDK (Cloud Development Kit)",summary:"TypeScript·Python 등 익숙한 프로그래밍 언어로 인프라를 코드로 정의합니다.",services:[{name:"Construct 재사용 컴포넌트",role:"인프라 패턴을 클래스로 정의",connects:"→ 팀 표준 패턴 공유 쉬움"},{name:"자동 CloudFormation 변환",role:"CDK 코드 → CloudFormation 스택으로 자동 변환",connects:"→ AWS 네이티브 배포"}],flow:"CDK 코드 작성 → cdk synth → cdk deploy → 인프라 생성",tip:"AWS 서비스에 집중하고 프로그래밍 언어가 익숙하다면 CDK가 편리합니다."},
  cfn:{title:"AWS CloudFormation",summary:"JSON/YAML 템플릿으로 AWS 인프라를 정의하는 AWS 기본 도구입니다.",services:[{name:"스택",role:"관련 리소스를 하나로 묶어 관리",connects:"→ 스택 삭제 시 모든 리소스 자동 삭제"},{name:"Change Set",role:"적용 전 변경사항 미리 보기",connects:"→ 예상치 못한 삭제·변경 사전 확인"}],flow:"YAML 템플릿 작성 → Change Set 미리보기 → 스택 업데이트 → 인프라 반영",tip:"YAML이 길어지면 관리가 어렵습니다. CDK 또는 Terraform으로 넘어가는 경우가 많습니다."},
  manual_deploy:{title:"수동 배포",summary:"AWS 콘솔이나 CLI를 직접 사용해 수동으로 배포합니다.",services:[{name:"AWS 콘솔",role:"웹 UI로 직접 배포",connects:"→ 즉시 시작 가능·학습에 용이"}],flow:"수동 작업 → AWS 콘솔/CLI → 배포 완료",tip:"작은 팀의 초기 단계에서는 수동 배포로 시작해도 됩니다. 배포가 잦아지면 CI/CD를 도입하세요."},
  codepipeline:{title:"AWS CodePipeline",summary:"AWS 네이티브 CI/CD 파이프라인입니다. CodeBuild·CodeDeploy와 함께 완전 AWS 생태계 내 CI/CD를 구성합니다.",services:[{name:"CodePipeline",role:"파이프라인 오케스트레이터",connects:"→ Source → Build → Deploy 단계 연결"},{name:"CodeBuild",role:"빌드 서버",connects:"→ 도커 이미지 빌드·단위 테스트 실행"},{name:"CodeDeploy",role:"배포 자동화",connects:"→ ECS Blue/Green·EC2 롤링 배포"}],flow:"코드 커밋 → CodePipeline 트리거 → CodeBuild(빌드) → CodeDeploy(배포) → 서비스 업데이트",tip:"AWS 생태계 안에서만 쓴다면 IAM 통합이 자연스럽습니다."},
  github:{title:"GitHub Actions (CI/CD)",summary:"GitHub 저장소에 코드를 올리면 자동으로 테스트·빌드·배포가 실행됩니다.",services:[{name:"워크플로 YAML",role:"코드 푸시·PR 시 자동 실행되는 파이프라인 정의",connects:"→ .github/workflows/ 폴더에 작성"},{name:"GitHub Marketplace",role:"수천 개의 사전 제작된 액션",connects:"→ AWS 배포·테스트·알림 등 즉시 사용"}],flow:"코드 푸시 → 워크플로 자동 실행 → 빌드·테스트 → ECR 푸시 → ECS 배포",tip:"GitHub를 쓰고 있다면 GitHub Actions가 별도 CI/CD 서버 없이 가장 편리합니다."},
  gitlab:{title:"GitLab CI/CD",summary:"GitLab 저장소와 통합된 CI/CD 파이프라인입니다. 사내 GitLab을 쓰는 팀에 적합합니다.",services:[{name:".gitlab-ci.yml",role:"파이프라인 정의 파일",connects:"→ stages·jobs로 파이프라인 구성"},{name:"Environments",role:"dev·staging·prod 배포 환경 관리",connects:"→ 수동 승인으로 운영 배포 보호"}],flow:"코드 푸시 → .gitlab-ci.yml 실행 → 빌드·테스트 → 배포",tip:"GitLab은 코드 저장소·CI/CD·이슈 관리·보안 스캔이 하나에 통합된 올인원 플랫폼입니다."},
  git_only:{title:"Git 저장소만 (CI/CD 없음)",summary:"코드 버전 관리는 하지만 자동 배포 파이프라인은 없습니다.",services:[{name:"Git",role:"코드 버전 관리",connects:"→ 변경 이력 추적·협업 가능"}],flow:"코드 변경 → Git 커밋 → 수동으로 서버에 배포",tip:"초기에는 괜찮지만 팀이 커지면 수동 배포는 오류와 충돌의 원인이 됩니다. GitHub Actions 등을 조기에 도입하세요."},
  bluegreen:{title:"Blue/Green 배포",summary:"현재 운영 중인 서버(Blue)와 새 버전 서버(Green)를 동시에 올려두고 트래픽을 순간 전환합니다.",services:[{name:"Blue 환경",role:"현재 운영 중인 서버",connects:"→ 전환 전까지 100% 트래픽"},{name:"Green 환경",role:"새 버전 서버 사전 테스트 완료",connects:"→ 트래픽 전환 전 마지막 검증"},{name:"순간 트래픽 전환",role:"ALB 가중치 0% → 100% 전환",connects:"→ 서비스 중단 없이 버전 교체"}],flow:"Green 서버 준비 → 테스트 → ALB 트래픽 전환 → 문제 시 Blue로 즉시 롤백",tip:"ALB 설정 변경 한 번으로 이전 버전으로 즉시 되돌아갑니다."},
  rolling:{title:"롤링 배포",summary:"서버를 하나씩 순서대로 새 버전으로 교체합니다. 배포 중에도 서비스가 유지됩니다.",services:[{name:"단계적 교체",role:"서버 1/4씩 순서대로 교체",connects:"→ 배포 중에도 75% 서버는 정상 운영"},{name:"최소 실행 수 유지",role:"ECS minHealthyPercent 설정",connects:"→ 배포 중 최소 서버 수 보장"}],flow:"서버 1 교체 → 정상 확인 → 서버 2 교체 → 모든 서버 교체 완료",tip:"롤링 배포 중에는 구버전과 신버전이 동시에 운영됩니다. API 변경은 하위 호환성을 유지해야 합니다."},
  canary:{title:"카나리 배포",summary:"트래픽의 일부(예: 5%)만 새 버전으로 보내고 문제가 없으면 점진적으로 늘려갑니다.",services:[{name:"가중치 기반 라우팅",role:"ALB 또는 Route 53으로 트래픽 비율 조절",connects:"→ 5% → 20% → 50% → 100% 단계적 전환"},{name:"모니터링",role:"카나리 서버 에러율·지연시간 실시간 감시",connects:"→ 이상 감지 시 즉시 0%로 롤백"}],flow:"신버전 5% 트래픽 → 에러율 확인 → 정상이면 20% → 100%",tip:"카나리 배포는 실제 사용자 트래픽으로 새 버전을 검증하므로 가장 안전합니다."},
  dev_prod:{title:"Dev + Prod 2개 환경",summary:"개발 환경과 운영 환경만 분리합니다. 소규모 팀의 최소 구성입니다.",services:[{name:"Dev 환경",role:"개발·테스트용",connects:"→ 작은 인스턴스·단일 AZ"},{name:"Prod 환경",role:"실제 사용자 서비스",connects:"→ Multi-AZ·오토스케일링·모니터링"}],flow:"개발 → Dev 배포·테스트 → Prod 배포",tip:"최소한 Dev → Prod 2단계는 유지하세요."},
  three:{title:"Dev + Staging + Prod 3개 환경",summary:"개발·검증·운영 3단계로 나눕니다. 대부분의 운영 서비스에서 권장하는 구성입니다.",services:[{name:"Dev 환경",role:"개발자 자유로운 테스트",connects:"→ 자주 배포·빠른 피드백"},{name:"Staging 환경",role:"운영과 동일한 환경에서 최종 검증",connects:"→ 운영 배포 전 승인 게이트"},{name:"Prod 환경",role:"실제 사용자 서비스",connects:"→ 변경 최소화·안정성 최우선"}],flow:"코드 완성 → Dev 테스트 → Staging 검증 → 승인 → Prod 배포",tip:"Staging은 Prod와 동일한 인프라 규모로 유지해야 실제 의미가 있습니다."},
  four:{title:"Dev + Staging + QA + Prod 4개 환경",summary:"QA 전담팀이 있는 경우의 구성입니다.",services:[{name:"QA 환경",role:"전담 QA팀의 테스트 환경",connects:"→ 개발팀과 독립적인 검증"}],flow:"코드 완성 → Dev → QA 테스트 → Staging 검증 → Prod 배포",tip:"QA 환경은 QA팀이 테스트하는 동안 개발팀이 다음 기능을 개발할 수 있도록 독립적으로 관리되어야 합니다."},
  cost_first:{title:"비용 최우선",summary:"성능·편의성 일부를 희생하더라도 인프라 비용을 최소화합니다.",services:[{name:"Spot 인스턴스",role:"빈 서버 활용으로 최대 90% 절감",connects:"→ 중단 가능성 있어 Stateless 서비스만"},{name:"Reserved Instance 3년",role:"최대 72% 할인",connects:"→ 장기 약정 필요"}],flow:"모든 설정을 비용 최소화 방향으로",tip:"핵심 서비스(DB·결제)는 비용 절감에서 제외하세요."},
  balanced:{title:"비용과 성능 균형",summary:"비용 절감과 성능/안정성을 균형 있게 추구합니다. 대부분의 서비스에 적합합니다.",services:[{name:"Savings Plans",role:"특정 인스턴스 타입 제약 없이 비용 절감",connects:"→ Fargate·Lambda도 적용 가능"},{name:"Auto Scaling",role:"필요할 때만 서버 추가",connects:"→ 유휴 시간 비용 절감"}],flow:"비용 최적화 + 성능 유지 + 안정성 확보 균형",tip:"대부분의 서비스에서 가장 현실적인 선택입니다."},
  perf_first:{title:"성능/안정성 최우선",summary:"비용이 더 들더라도 최고의 성능과 안정성을 추구합니다.",services:[{name:"On-Demand 인스턴스",role:"즉시 확장·중단 없음",connects:"→ Spot보다 비싸지만 안정적"},{name:"3개 AZ 분산",role:"AZ 장애에도 서비스 유지",connects:"→ 최고 가용성"}],flow:"모든 설정을 안정성·성능 최대화 방향으로",tip:"성능 최우선은 비용이 2~3배 올라갈 수 있습니다."},
  latency:{title:"지연시간 최소화",summary:"사용자 응답 속도를 최대한 빠르게 줄이는 방향입니다.",services:[{name:"CloudFront",role:"전 세계 엣지에서 콘텐츠 제공",connects:"→ 사용자 근처에서 즉시 응답"},{name:"ElastiCache",role:"DB 쿼리 없이 캐시에서 즉시 응답",connects:"→ 1ms 이내 응답"}],flow:"요청 → CloudFront 캐시 히트 시 즉시 응답 → Redis → DB",tip:"사용자 체감 속도는 서버 성능보다 네트워크 거리(지연시간)가 더 큰 영향을 줍니다."},
  heavy:{title:"대용량 데이터 처리 특화",summary:"수TB 이상의 데이터를 처리하거나 분석하는 서비스에 최적화합니다.",services:[{name:"S3 + Glacier",role:"무제한 저렴한 스토리지",connects:"→ 오래된 데이터 자동 아카이빙"},{name:"Redshift / Athena",role:"수TB 데이터 분석 쿼리",connects:"→ RDS로는 처리 불가한 대용량 분석"}],flow:"원시 데이터 → S3 → Glue ETL → Redshift/Athena 분석 → 결과 시각화",tip:"대용량 데이터 처리는 일반 서비스와 아키텍처가 완전히 다릅니다."},
  "1yr":{title:"1년 약정 (Reserved Instance)",summary:"1년간 사용을 약정하고 On-Demand 대비 약 40% 할인을 받습니다.",services:[{name:"EC2 RI / Aurora RI",role:"1년 약정",connects:"→ On-Demand 대비 약 40% 절감"},{name:"Compute Savings Plans",role:"특정 인스턴스 타입 제약 없이 절감",connects:"→ Fargate·Lambda도 적용"}],flow:"안정적 서비스 → 1년 약정 → 40% 할인 적용",tip:"서비스가 안정화되고 1년 이상 운영할 확신이 있다면 RI로 비용을 크게 절감할 수 있습니다."},
  "3yr":{title:"3년 약정 (최대 할인)",summary:"3년간 사용을 약정하고 On-Demand 대비 최대 72% 할인을 받습니다.",services:[{name:"3년 약정",role:"최대 72% 할인",connects:"→ 장기 운영 서비스에 최대 효율"}],flow:"안정적 서비스 → 3년 약정 → 최대 72% 할인 적용",tip:"3년 약정은 신중하게 결정하세요. 서비스 방향 변경이 생기면 약정이 낭비됩니다."},
  partial:{title:"부분 Spot 활용",summary:"메인 서버는 On-Demand로 운영하고 배치·스케일아웃 서버에만 Spot을 활용합니다.",services:[{name:"On-Demand 기본 서버",role:"핵심 서비스 안정적 운영",connects:"→ Spot 중단 영향 없음"},{name:"Spot 보조 서버",role:"트래픽 피크 시 추가 서버",connects:"→ 중단돼도 메인 서버가 처리"}],flow:"기본 서버(On-Demand) → 트래픽 증가 → Spot 서버 추가 → 피크 처리",tip:"가장 균형 잡힌 접근입니다."},

  "99":{title:"가용성 99% (연간 3일 9시간 다운 허용)",summary:"1년에 약 3일 9시간 장애가 나도 괜찮은 수준. 내부 도구나 개발 환경에 적합합니다.",services:[{name:"단일 AZ 구성",role:"비용 최소화",connects:"→ 장애 시 수동 복구"}],flow:"서버 장애 → 수동 재시작 → 서비스 재개",tip:"99% 가용성은 생각보다 낮습니다. 외부 사용자가 있다면 최소 99.9%를 목표로 하세요."},
  "99.9":{title:"가용성 99.9% (연간 8.7시간 다운 허용)",summary:"1년에 약 8.7시간 장애가 나도 괜찮은 수준. 일반적인 B2C·B2B 서비스의 표준입니다.",services:[{name:"Multi-AZ DB",role:"DB 장애 시 30초 내 자동 전환",connects:"→ 가장 큰 단일 장애점 제거"},{name:"ECS 최소 2 Task",role:"서버 1개 죽어도 서비스 유지",connects:"→ ALB가 자동으로 정상 서버로 라우팅"}],flow:"서버 장애 → ALB 헬스체크 감지 → 정상 서버로 트래픽 전환",tip:"Multi-AZ DB와 ECS 최소 2 Task만 설정해도 99.9% 가용성을 달성할 수 있습니다."},
  "99.95":{title:"가용성 99.95% (연간 4.4시간 다운 허용)",summary:"금융·이커머스 수준의 높은 가용성. Multi-AZ 풀 구성과 Auto Scaling이 필요합니다.",services:[{name:"Multi-AZ ALB + ECS",role:"AZ 1개 장애 시 다른 AZ가 자동 대응",connects:"→ AZ 단위 장애에도 서비스 유지"},{name:"Aurora Multi-AZ",role:"DB 자동 페일오버 30초 이내",connects:"→ DB 장애 자동 복구"},{name:"Route 53 헬스체크",role:"이상 감지 즉시 트래픽 전환",connects:"→ DNS 레벨 자동 복구"}],flow:"AZ 장애 → ALB 자동 회피 → Route 53 전환 → 서비스 지속",tip:"99.95%를 위해서는 최소 2개 AZ에 걸친 구성이 필수입니다."},
  "99.99":{title:"가용성 99.99% (연간 52분 다운 허용)",summary:"증권·은행·결제 수준의 최고 가용성. 3 AZ 풀 분산과 DR 전략이 필요합니다.",services:[{name:"3개 AZ 풀 분산",role:"AZ 1개 전체 장애에도 서비스 유지",connects:"→ AWS 리전 내 최대 분산"},{name:"Aurora Global",role:"리전 장애 시 1분 내 전환",connects:"→ 리전 단위 재해 대응"},{name:"Multi-Region Active-Passive",role:"DR 리전 상시 대기",connects:"→ 리전 전체 재해 대응"}],flow:"리전 장애 → Route 53 자동 전환 → DR 리전 서비스",tip:"99.99%는 앱 코드의 멱등성, 회로 차단기 패턴 등 코드 레벨 대응이 함께 필요합니다."},
  "15min":{title:"RPO 15분 이내",summary:"최대 15분치 데이터를 잃어도 괜찮은 수준. Aurora 기본 설정으로 달성 가능합니다.",services:[{name:"Aurora 연속 백업",role:"5분 간격 WAL 로그 + 자동 스냅샷",connects:"→ 임의 시점 복구(PITR) 가능"}],flow:"데이터 입력 → 5분마다 WAL 저장 → 장애 시 원하는 시점으로 복구",tip:"Aurora는 기본적으로 5분 단위 PITR을 지원합니다. 설정 없이도 15분 RPO를 달성할 수 있습니다."},
  "1h":{title:"RPO 1시간 이내",summary:"최대 1시간치 데이터를 잃어도 괜찮은 수준. 시간 단위 스냅샷으로 달성 가능합니다.",services:[{name:"RDS 자동 스냅샷",role:"매시간 스냅샷",connects:"→ 선택한 시점으로 복구"}],flow:"데이터 입력 → 매시간 스냅샷 → 장애 시 최근 스냅샷으로 복구",tip:"RDS 자동 스냅샷 보존 기간을 최소 7일로 설정하세요. 기본값은 1일입니다."},
  "24h":{title:"RPO 24시간 이내",summary:"최대 하루치 데이터를 잃어도 괜찮은 수준. 일반 내부 도구나 캐시성 서비스에 적합합니다.",services:[{name:"일간 RDS 스냅샷",role:"매일 자동 백업",connects:"→ AWS가 자동으로 백업 실행"}],flow:"데이터 입력 → 매일 스냅샷 → 장애 시 어제 데이터로 복구",tip:"24시간 RPO라도 스냅샷 복구 테스트를 반기 1회 실시해 실제로 복구가 되는지 확인하세요."},
  "1az":{title:"단일 AZ (1개 가용 영역)",summary:"하나의 데이터센터에만 서버를 두는 구성. 비용이 가장 저렴하지만 AZ 장애 시 전체 서비스가 중단됩니다.",services:[{name:"단일 AZ 서버",role:"비용 최소화",connects:"→ AZ 장애 시 서비스 전체 중단"}],flow:"서버 → 단일 AZ → 서비스",tip:"1 AZ는 운영 서비스에 권장하지 않습니다. 비용 절감 목적이라면 2 AZ + 공유 NAT GW를 고려하세요."},
  "2az":{title:"2개 AZ (표준 분산 구성)",summary:"2개의 데이터센터에 서버를 분산합니다. 비용과 안정성의 최적 균형점입니다.",services:[{name:"ALB + ECS Multi-AZ",role:"AZ 1개 장애 시 다른 AZ가 자동 대응",connects:"→ 서비스 중단 없이 계속 운영"},{name:"NAT GW 2개",role:"AZ별 독립 출구",connects:"→ AZ 장애 시 다른 AZ 영향 없음"}],flow:"AZ-A 서버 + AZ-B 서버 → ALB가 분산 처리",tip:"2 AZ가 비용 대비 가용성의 최적점입니다. 99.9~99.95% 가용성 달성에 충분합니다."},
  "3az":{title:"3개 AZ (최고 수준 분산)",summary:"3개의 데이터센터에 서버를 분산합니다. 1개 AZ가 통째로 죽어도 나머지 2개로 서비스가 유지됩니다.",services:[{name:"ALB + ECS 3개 AZ",role:"AZ 1개 완전 장애에도 서비스 유지",connects:"→ 99.95~99.99% 가용성"},{name:"Aurora 3개 AZ",role:"DB 데이터 3중 복제",connects:"→ 최고 수준 데이터 안정성"}],flow:"3개 AZ 분산 → AZ 1개 장애 시 나머지 2개로 트래픽 자동 이동",tip:"3 AZ는 NAT GW 비용이 3배가 됩니다. 고가용성이 정말 필요한 운영 환경에서만 선택하세요."},
  "2tier":{title:"2계층 서브넷 (퍼블릭 + 프라이빗)",summary:"인터넷에 노출되는 퍼블릭과 격리된 프라이빗 서브넷으로 나눕니다. 가장 일반적인 구성입니다.",services:[{name:"퍼블릭 서브넷",role:"ALB·NAT GW만 위치",connects:"→ 인터넷 직접 접근 가능"},{name:"프라이빗 서브넷",role:"앱 서버·DB 위치",connects:"→ 인터넷에서 직접 접근 불가"}],flow:"인터넷 → ALB(퍼블릭) → 앱(프라이빗) → DB(프라이빗)",tip:"대부분의 서비스에 충분한 구성입니다. DB는 Security Group으로 앱 서버만 접근 허용하세요."},
  "3tier":{title:"3계층 서브넷 (퍼블릭 + 프라이빗 + 격리)",summary:"DB를 앱 서버와도 완전히 격리된 별도 서브넷에 둡니다. 금융·의료·공공 서비스의 보안 강화 구성입니다.",services:[{name:"퍼블릭 서브넷",role:"ALB·NAT GW만",connects:"→ 인터넷 직접 접근"},{name:"프라이빗 서브넷",role:"앱 서버·캐시",connects:"→ 앱만 접근 가능"},{name:"격리 서브넷",role:"DB만 위치",connects:"→ 앱 서버만 접근 허용"}],flow:"인터넷 → ALB(퍼블릭) → 앱(프라이빗) → DB(격리)",tip:"PCI DSS, HIPAA 등 규정 준수 환경에서는 3계층 구성이 권장됩니다."},
  senior:{title:"AWS 고급 (Senior)",summary:"EKS, 멀티 계정, CDK 등 고급 AWS 서비스를 능숙하게 사용합니다.",services:[{name:"EKS + Karpenter",role:"컨테이너 오케스트레이션 고급 운영",connects:"→ 수백 개 Pod 정밀 관리"},{name:"CDK / Terraform",role:"인프라를 코드로 완전 관리",connects:"→ 모든 리소스 버전 관리·자동화"}],flow:"코드 변경 → CI/CD → Terraform Plan → Apply → 모니터링",tip:"고급 단계에서는 Platform Engineering 관점에서 개발팀이 셀프서비스로 인프라를 요청할 수 있는 체계를 만드는 것이 효율적입니다."},
  b2c:{title:"B2C (일반 소비자 서비스)",summary:"일반 개인 사용자를 대상으로 하는 서비스입니다. 예상치 못한 트래픽 폭증과 빠른 응답속도가 핵심입니다.",services:[{name:"CloudFront",role:"전 세계 빠른 콘텐츠 제공",connects:"→ 사용자 근처 엣지에서 캐시 응답"},{name:"Auto Scaling",role:"갑작스런 트래픽 자동 대응",connects:"→ 사용자 수 증가에 맞게 서버 자동 확장"}],flow:"사용자 → CloudFront(캐시) → ALB → 서버(Auto Scaling) → DB",tip:"B2C 서비스는 예측 불가한 바이럴을 항상 염두에 두고 설계하세요. CloudFront 캐시가 갑작스런 폭증의 첫 번째 방어선입니다."},
  b2b:{title:"B2B (기업 대상 서비스)",summary:"기업 고객이 사용하는 서비스입니다. 안정성·보안·SLA 준수가 B2C보다 훨씬 중요합니다.",services:[{name:"Multi-AZ 구성",role:"계약 SLA 준수",connects:"→ 기업 고객 다운타임 페널티 방지"},{name:"IAM + SSO",role:"기업 계정 연동·권한 관리",connects:"→ 고객사 Active Directory 연동"},{name:"전용 테넌트 격리",role:"고객사 데이터 완전 분리",connects:"→ 멀티 테넌시 또는 전용 인프라"}],flow:"기업 사용자 → VPN/SSO → 전용 테넌트 → DB(격리)",tip:"B2B는 한 명의 기업 고객이 계약 해지하면 큰 손실입니다. 99.9% 이상 가용성 SLA와 명확한 장애 대응 프로세스를 미리 만드세요."},
  karpenter:{title:"Karpenter (지능형 노드 자동 확장)",summary:"필요한 Pod에 딱 맞는 EC2 노드를 수초 내에 자동으로 추가합니다. 기존 Cluster Autoscaler보다 훨씬 빠르고 효율적입니다.",services:[{name:"Karpenter",role:"Pod 요청에 맞게 EC2 노드 즉시 추가",connects:"→ Spot·On-Demand 혼합 자동 관리"}],flow:"Pod 생성 요청 → Karpenter가 최적 노드 유형 선택 → EC2 시작(20~30초) → Pod 배치",tip:"Karpenter는 Cluster Autoscaler보다 노드 프로비저닝이 2~3배 빠릅니다. EKS 신규 구성이라면 Karpenter를 기본으로 선택하세요."},
  cluster_autoscaler:{title:"Cluster Autoscaler (기존 노드 자동 확장)",summary:"EKS에서 오래 사용해온 노드 자동 확장 도구입니다. ASG 기반으로 노드를 늘리고 줄입니다.",services:[{name:"Cluster Autoscaler",role:"ASG를 통한 EC2 노드 확장",connects:"→ 미리 정의한 ASG 내에서 확장"}],flow:"Pod 스케줄링 실패 → Cluster Autoscaler 감지 → ASG 증가 → 노드 추가",tip:"신규 프로젝트라면 Karpenter를 추천합니다. 기존 EKS 클러스터가 있다면 마이그레이션 비용 대비 Karpenter 장점을 검토하세요."},
  fargate:{title:"EKS Fargate (서버리스 노드)",summary:"EC2 서버 관리 없이 Pod를 서버리스로 실행합니다. 노드 패치·관리가 불필요합니다.",services:[{name:"Fargate Profile",role:"지정한 네임스페이스의 Pod를 서버리스로 실행",connects:"→ EC2 노드 관리 불필요"}],flow:"Pod 생성 → Fargate가 격리된 컴퓨팅에서 실행 → 자동 관리",tip:"EKS Fargate는 EC2 노드보다 2~3배 비쌉니다. 소규모 또는 관리 부담을 줄이고 싶을 때 적합합니다."},
  alb_controller:{title:"AWS Load Balancer Controller",summary:"EKS에서 Ingress를 생성하면 ALB를 자동으로 만들어 줍니다. AWS 네이티브 로드 밸런서를 K8s에서 직접 사용합니다.",services:[{name:"AWS LB Controller",role:"Ingress → ALB 자동 생성",connects:"→ AWS WAF·Shield 통합 가능"},{name:"TargetGroupBinding",role:"기존 ALB TG에 Pod 직접 연결",connects:"→ IP 타겟 모드로 고성능 라우팅"}],flow:"Ingress 생성 → Controller가 ALB 자동 프로비저닝 → 트래픽 수신",tip:"EKS에서 Ingress 쓸 때는 AWS LB Controller가 가장 AWS 친화적인 선택입니다."},
  nginx:{title:"Nginx Ingress Controller",summary:"오픈소스 Nginx를 EKS Ingress로 사용합니다. 세밀한 트래픽 제어와 다양한 플러그인을 지원합니다.",services:[{name:"Nginx Ingress",role:"HTTP 라우팅·리다이렉트·리라이트",connects:"→ 복잡한 URL 라우팅 규칙 적용 가능"}],flow:"요청 → Nginx Pod → 서비스 라우팅",tip:"AWS 외 환경(온프레미스 등)과 호환성이 필요하거나 Nginx 고급 기능이 필요할 때 선택합니다."},
  traefik:{title:"Traefik Ingress Controller",summary:"서비스 디스커버리와 자동 TLS 갱신이 강점인 최신 Ingress Controller입니다.",services:[{name:"Traefik",role:"자동 라우팅 설정·Let's Encrypt 자동 갱신",connects:"→ 설정 최소화, 자동 디스커버리"}],flow:"새 서비스 배포 → Traefik이 자동으로 라우팅 규칙 등록",tip:"개발 환경이나 스타트업에서 설정을 최소화하고 싶을 때 좋은 선택입니다."},
  istio:{title:"Istio (풀 서비스 메시)",summary:"모든 서비스 간 통신을 자동으로 암호화하고 트래픽을 세밀하게 제어합니다. 강력하지만 운영 복잡도가 높습니다.",services:[{name:"Envoy 사이드카 프록시",role:"각 Pod에 자동 주입되는 프록시",connects:"→ 서비스 간 통신 투명하게 제어"},{name:"Istiod",role:"전체 메시 제어 플레인",connects:"→ 정책·인증서·라우팅 중앙 관리"}],flow:"서비스 A → Envoy 프록시 → mTLS 암호화 → 서비스 B의 Envoy → 서비스 B",tip:"Istio는 운영 복잡도가 매우 높습니다. AWS App Mesh나 단순 네트워크 폴리시로 충분한지 먼저 검토하세요."},
  aws_app_mesh:{title:"AWS App Mesh",summary:"AWS가 관리하는 서비스 메시입니다. Istio보다 단순하고 AWS 서비스와의 통합이 뛰어납니다.",services:[{name:"App Mesh",role:"ECS·EKS·EC2 간 통신 제어",connects:"→ AWS CloudMap과 통합"}],flow:"서비스 A → App Mesh Virtual Node → 서비스 B",tip:"AWS 환경에만 있다면 App Mesh가 Istio보다 운영이 단순합니다."},
  argocd:{title:"Argo CD (GitOps CD)",summary:"Git 저장소를 진실의 원천으로 삼아 K8s 클러스터 상태를 자동으로 동기화합니다.",services:[{name:"Argo CD",role:"Git의 선언적 설정을 클러스터에 자동 적용",connects:"→ Git 변경 → 자동 배포"}],flow:"코드 커밋 → Git 저장소 변경 → Argo CD 감지 → 클러스터 동기화",tip:"GitOps를 처음 도입한다면 Argo CD가 Flux보다 UI가 있어 학습이 쉽습니다."},
  flux:{title:"Flux (GitOps CD)",summary:"Argo CD와 같은 GitOps 도구이지만 더 가볍고 Helm 통합이 강합니다.",services:[{name:"Flux",role:"Git 변경 → K8s 자동 동기화",connects:"→ HelmRelease·Kustomization 지원"}],flow:"코드 커밋 → Flux가 감지 → 클러스터에 자동 적용",tip:"Helm 차트 기반 배포를 주로 한다면 Flux의 HelmRelease가 강력합니다."},
  prometheus_grafana:{title:"Prometheus + Grafana (오픈소스 모니터링)",summary:"K8s의 표준 모니터링 스택입니다. 메트릭 수집·저장·시각화·알림을 모두 담당합니다.",services:[{name:"Prometheus",role:"Pod·노드·앱 메트릭 수집·저장",connects:"→ 모든 K8s 컴포넌트 자동 수집"},{name:"Grafana",role:"메트릭 시각화 대시보드",connects:"→ CPU·메모리·요청수 실시간 차트"},{name:"AlertManager",role:"임계값 초과 시 알림",connects:"→ Slack·PagerDuty·이메일 연동"}],flow:"앱 → Prometheus 수집(15초 간격) → Grafana 시각화 → AlertManager 알림",tip:"kube-prometheus-stack Helm 차트로 한 번에 설치 가능합니다."},
  cloudwatch:{title:"CloudWatch Container Insights (AWS 네이티브 모니터링)",summary:"별도 설치 없이 EKS 메트릭을 CloudWatch에서 바로 볼 수 있습니다. AWS 서비스와 통합이 뛰어납니다.",services:[{name:"CloudWatch Container Insights",role:"EKS 메트릭·로그 자동 수집",connects:"→ 기존 CloudWatch 알람·대시보드 활용"},{name:"CloudWatch Logs",role:"컨테이너 로그 중앙 집계",connects:"→ CloudWatch Insights로 쿼리 가능"}],flow:"EKS → CloudWatch Agent → CloudWatch → 알람·대시보드",tip:"AWS에 올인하는 팀이라면 CloudWatch가 추가 도구 없이 쓸 수 있어 편리합니다."},
  opa_gatekeeper:{title:"OPA Gatekeeper (정책 엔진)",summary:"K8s에 배포할 수 있는 리소스의 규칙을 정의하고 자동으로 강제합니다. 예: latest 태그 금지, 최소 리소스 리밋 필수.",services:[{name:"Gatekeeper",role:"Policy를 자동으로 모든 배포에 강제",connects:"→ 위반 시 배포 자동 거부"}],flow:"배포 요청 → Gatekeeper 정책 검사 → 통과/거부",tip:"보안 팀이 요구하는 모든 K8s 규정 준수 요건을 코드로 관리할 수 있어 규정 준수 서비스에 필수입니다."},
  kyverno:{title:"Kyverno (K8s 네이티브 정책)",summary:"OPA Gatekeeper와 비슷한 정책 엔진이지만 YAML로 정책을 작성해 K8s에 더 친숙합니다.",services:[{name:"Kyverno",role:"YAML 기반 정책으로 배포 규칙 강제",connects:"→ 자동 레이블 추가, 리소스 변환도 가능"}],flow:"배포 요청 → Kyverno 정책 검사 → 통과/변환/거부",tip:"OPA는 Rego 언어를 배워야 하지만 Kyverno는 YAML로 작성해 진입 장벽이 낮습니다."},
  psa:{title:"Pod Security Admission (내장 보안)",summary:"K8s 내장 보안 정책입니다. Privileged/Baseline/Restricted 3단계로 Pod 보안 수준을 강제합니다.",services:[{name:"Pod Security Admission",role:"네임스페이스 단위로 보안 수준 강제",connects:"→ 추가 도구 없이 K8s 기본 제공"}],flow:"Pod 생성 → PSA 보안 수준 검사 → 위반 시 거부/경고",tip:"추가 도구 없이 기본 보안 기준을 적용할 수 있습니다. 더 세밀한 정책이 필요하면 Kyverno나 Gatekeeper를 추가하세요."},
  cilium:{title:"Cilium (eBPF 네트워크 정책)",summary:"eBPF 기술을 사용하는 고성능 K8s 네트워크 플러그인입니다. L7 정책과 뛰어난 가시성을 제공합니다.",services:[{name:"Cilium",role:"Pod 간 네트워크 정책 고성능 처리",connects:"→ eBPF로 커널 수준 처리"},{name:"Hubble",role:"네트워크 트래픽 실시간 가시성",connects:"→ 어떤 Pod가 어디에 요청하는지 시각화"}],flow:"Pod A → Cilium eBPF → 정책 검사 → Pod B",tip:"EKS에서 Cilium은 기본 VPC CNI를 대체합니다. 설치가 복잡하지만 고성능·고가시성이 필요할 때 가치 있습니다."},
  vpc_cni:{title:"AWS VPC CNI (기본 네트워크)",summary:"EKS의 기본 네트워크 플러그인입니다. Pod가 VPC IP를 직접 할당받아 AWS 서비스와 자연스럽게 통합됩니다.",services:[{name:"AWS VPC CNI",role:"Pod에 VPC IP 직접 할당",connects:"→ 별도 오버레이 네트워크 없이 AWS와 직접 통신"}],flow:"Pod 생성 → VPC ENI에서 IP 할당 → VPC 내 직접 라우팅",tip:"특별한 이유가 없다면 기본 VPC CNI를 사용하세요. AWS 서비스(RDS, ElastiCache 등)와의 통신이 가장 단순합니다."},
  secrets_csi:{title:"Secrets Store CSI Driver",summary:"AWS Secrets Manager나 Parameter Store의 시크릿을 K8s Pod에 파일 또는 환경변수로 자동 주입합니다.",services:[{name:"Secrets Store CSI",role:"AWS Secrets Manager 시크릿을 Pod에 마운트",connects:"→ 코드에 시크릿 하드코딩 불필요"},{name:"AWS Secrets Manager",role:"시크릿 중앙 관리·자동 순환",connects:"→ 30일마다 비밀번호 자동 교체"}],flow:"Pod 시작 → CSI Driver가 Secrets Manager 조회 → 시크릿을 파일로 마운트 → 앱 읽기",tip:"K8s Secret보다 보안이 강합니다. DB 비밀번호, API 키 등 모든 시크릿을 Secrets Manager로 관리하세요."},
  external_secrets:{title:"External Secrets Operator",summary:"AWS Secrets Manager·SSM Parameter Store의 시크릿을 K8s Secret으로 자동 동기화합니다.",services:[{name:"External Secrets Operator",role:"외부 시크릿 스토어 → K8s Secret 자동 생성",connects:"→ 시크릿 변경 시 자동 업데이트"}],flow:"Secrets Manager 시크릿 → ESO가 감지·동기화 → K8s Secret 자동 생성",tip:"CSI Driver와 달리 기존 앱 코드가 K8s Secret을 사용한다면 External Secrets로 더 쉽게 마이그레이션 가능합니다."},
  velero:{title:"Velero (K8s 백업·복구)",summary:"EKS 클러스터 전체(네임스페이스, PVC 포함)를 S3에 백업하고 복구합니다.",services:[{name:"Velero",role:"K8s 리소스 + 볼륨 데이터 백업",connects:"→ S3에 스냅샷 저장"},{name:"S3 Backup 버킷",role:"백업 파일 저장",connects:"→ 다른 리전에 백업 복제 가능"}],flow:"스케줄 백업 → Velero가 K8s 오브젝트 + PVC 스냅샷 → S3 저장",tip:"클러스터 전체 재해 복구 시나리오를 위해 Velero 복구 절차를 분기 1회 테스트하세요."},
  hpa_only:{title:"HPA만 (Pod 수 자동 조절)",summary:"트래픽에 따라 Pod 수를 자동으로 늘리고 줄입니다. K8s의 가장 기본적인 자동 확장 방식입니다.",services:[{name:"HPA",role:"CPU/메모리 기준으로 Pod 수 자동 조절",connects:"→ 트래픽 증가 시 Pod 수평 확장"}],flow:"CPU 70% 초과 → HPA 감지 → 새 Pod 생성(30초~1분) → 트래픽 분산",tip:"대부분의 서비스에 충분한 기본 설정입니다. min: 2, max: 10, CPU 70% 기준으로 시작하세요."},
  hpa_keda:{title:"HPA + KEDA (이벤트 기반 확장)",summary:"CPU 외에 SQS 메시지 수, DB 쿼리 수 등 비즈니스 메트릭으로 Pod를 확장합니다.",services:[{name:"KEDA",role:"SQS·Kafka·DB 등 외부 메트릭으로 Pod 확장",connects:"→ 메시지 100개당 Pod 1개처럼 정밀 설정"},{name:"ScaledObject",role:"확장 기준 정의",connects:"→ 어떤 메트릭이 몇일 때 몇 개로 확장할지"}],flow:"SQS 메시지 증가 → KEDA 감지 → Pod 자동 확장 → 메시지 처리",tip:"배치 처리, 메시지 큐 소비자처럼 SQS나 Kafka 기반 워크로드에서 KEDA가 매우 유용합니다."},
  hpa_vpa:{title:"HPA + VPA (수평 + 수직 확장)",summary:"Pod 수(HPA)와 Pod별 CPU·메모리 크기(VPA) 모두 자동으로 최적화합니다.",services:[{name:"VPA",role:"각 Pod의 CPU·메모리 요청을 자동 최적화",connects:"→ 적정 리소스 자동 추천 및 적용"},{name:"HPA",role:"Pod 수 자동 조절",connects:"→ 트래픽에 맞게 Pod 수 확장"}],flow:"트래픽 증가 → HPA가 Pod 추가 + VPA가 Pod 크기 최적화",tip:"HPA와 VPA를 동시에 쓸 때는 CPU 기준 HPA와 VPA 충돌을 주의하세요. VPA는 메모리 기준으로만 쓰는 것이 안전합니다."},
  single_ns:{title:"단일 네임스페이스",summary:"모든 서비스를 하나의 K8s 네임스페이스에서 운영합니다. 소규모 팀에 단순합니다.",services:[{name:"단일 네임스페이스",role:"모든 서비스 한 곳 관리",connects:"→ 설정 단순·팀 간 경계 없음"}],flow:"모든 서비스 → 하나의 네임스페이스 → 관리",tip:"팀이 커지거나 서비스가 많아지면 네임스페이스 분리를 고려하세요. RBAC 권한 관리가 복잡해집니다."},
  separate:{title:"서비스별 네임스페이스 분리",summary:"서비스 또는 팀별로 네임스페이스를 나눕니다. 권한 관리와 리소스 격리에 유리합니다.",services:[{name:"서비스별 네임스페이스",role:"팀·서비스별 독립 공간",connects:"→ RBAC으로 팀별 접근 제어"},{name:"ResourceQuota",role:"네임스페이스별 CPU·메모리 상한",connects:"→ 한 서비스가 전체 자원 독점 방지"}],flow:"서비스 A(ns: payment) / 서비스 B(ns: user) → 격리된 공간에서 운영",tip:"DevOps 성숙도가 높아지면 네임스페이스를 팀 단위로 나누는 것이 표준입니다."},
  multi_cluster:{title:"멀티 클러스터 전략",summary:"환경(Prod/Stage/Dev)마다 또는 서비스 중요도마다 별도 EKS 클러스터를 운영합니다.",services:[{name:"Prod 클러스터",role:"운영 서비스 전용",connects:"→ Dev와 완전 격리"},{name:"Stage 클러스터",role:"운영 동일 환경 검증",connects:"→ 운영 배포 전 최종 테스트"},{name:"Dev 클러스터",role:"개발자 실험 환경",connects:"→ 자유로운 실험 허용"}],flow:"개발 → Dev 클러스터 → Stage 클러스터 검증 → Prod 클러스터 배포",tip:"클러스터가 늘어날수록 운영 복잡도도 올라갑니다. 아르고CD와 Terraform으로 클러스터 간 설정 일관성을 유지하세요."},
  native:{title:"AWS 네이티브 서비스 디스커버리",summary:"별도 도구 없이 AWS가 제공하는 네이티브 DNS와 서비스 디스커버리를 사용합니다.",services:[{name:"AWS Cloud Map",role:"서비스 이름 → IP 자동 등록·조회",connects:"→ ECS·Lambda·EC2 모두 지원"},{name:"Route 53 프라이빗 호스팅 존",role:"VPC 내부 전용 DNS",connects:"→ 서비스명으로 내부 통신"}],flow:"서비스 배포 → Cloud Map에 자동 등록 → 다른 서비스가 이름으로 호출",tip:"ECS 서비스 디스커버리는 Cloud Map을 자동으로 설정해줍니다. 별도 설정 없이 활성화 가능합니다."},
  url_path:{title:"URL 경로 기반 API 버저닝 (/v1/users)",summary:"URL에 버전 번호를 넣는 가장 일반적인 방법입니다. /v1/users → /v2/users처럼 명확하게 버전을 구분합니다.",services:[{name:"ALB 리스너 규칙",role:"/v1/, /v2/ 경로별 다른 서버로 라우팅",connects:"→ 버전별 서버 분리 가능"}],flow:"클라이언트 → /api/v2/users → ALB 경로 규칙 → v2 서버",tip:"가장 직관적이고 캐시하기 쉽습니다. 새 버전 출시 시 v1을 일정 기간 유지하고 Deprecation 공지를 미리 하세요."},
  subdomain:{title:"서브도메인 기반 API 버저닝 (v2.api.example.com)",summary:"서브도메인으로 버전을 구분합니다. v1.api.example.com, v2.api.example.com처럼 완전히 독립된 주소를 사용합니다.",services:[{name:"Route 53",role:"버전별 서브도메인 → 서버 라우팅",connects:"→ 버전별 완전 독립 운영 가능"}],flow:"v2.api.example.com → Route 53 → v2 서버",tip:"버전별로 완전히 다른 인프라가 필요할 때 유용합니다. 관리 포인트가 늘어나는 단점이 있습니다."},
  header:{title:"헤더 기반 API 버저닝 (Accept: application/v2+json)",summary:"URL은 동일하고 HTTP 헤더로 버전을 전달합니다. URL이 깔끔하지만 클라이언트 구현이 복잡합니다.",services:[{name:"API Gateway / ALB",role:"헤더 값에 따라 다른 서버로 라우팅",connects:"→ 같은 URL, 다른 처리"}],flow:"요청 + API-Version: 2 헤더 → API Gateway → 버전에 맞는 Lambda/서버",tip:"헤더 기반 버저닝은 캐시가 어렵습니다. CloudFront 캐시 키에 버전 헤더를 포함시켜야 합니다."},
  confluent_registry:{title:"Confluent Schema Registry",summary:"Kafka 메시지의 스키마(형식)를 중앙에서 관리합니다. 생산자·소비자 간 스키마 충돌을 방지합니다.",services:[{name:"Confluent Schema Registry",role:"Avro·Protobuf·JSON 스키마 중앙 관리",connects:"→ Kafka Producer가 메시지 보내기 전 검증"},{name:"Schema 버전 관리",role:"하위 호환성 자동 검사",connects:"→ Breaking Change 배포 방지"}],flow:"Producer → Schema Registry 검증 → Kafka 발행 → Consumer → Schema Registry 조회 → 역직렬화",tip:"Kafka를 쓴다면 Schema Registry는 필수입니다. 스키마 없이 운영하면 Consumer 장애가 빈번합니다."},
  glue_registry:{title:"AWS Glue Schema Registry",summary:"AWS가 관리하는 스키마 레지스트리입니다. MSK(Managed Kafka)와 Kinesis를 함께 쓸 때 AWS 네이티브 통합이 강점입니다.",services:[{name:"AWS Glue Schema Registry",role:"Avro·Protobuf·JSON 스키마 AWS 네이티브 관리",connects:"→ MSK·Kinesis와 자동 통합"},{name:"IAM 권한 관리",role:"스키마 접근 제어",connects:"→ AWS IAM으로 통합 관리"}],flow:"Producer → Glue Registry 검증 → MSK/Kinesis 발행",tip:"AWS 환경에 올인하는 팀이라면 Glue Registry가 Confluent보다 운영이 단순합니다."},
};

export function getInfoDb(lang: Lang = "ko"): Record<string, InfoEntry> {
  return lang === "en" ? INFO_DB_EN : INFO_DB_KO;
}

/** Backward-compatible default export (Korean) */
export const INFO_DB = INFO_DB_KO;
